import type { APIRoute } from "astro";

interface Example {
  owner: string;
  repo: string;
  description: string | null;
  language: string | null;
  avatarUrl: string | null;
  createdAt: number;
  stars: number | null;
}

// Intentionally the one public, unauthenticated read in the whole app —
// powers the logged-out gallery on cloud.deepdoc.tech's root. visibility is
// canonical on owner_repo_jobs (per-repo, single serving authority); the
// richer per-generation metadata (description/language/avatar/created_at)
// only lives on projects (per-user-owned row), so join back to the owner's
// own row to get it.
export const GET: APIRoute = async ({ locals }) => {
  const env = locals.runtime.env;

  const { results } = await env.DB.prepare(
    // p.status = 'done' — otherwise a repo still cloning/generating shows up
    // under "Previously generated by others" with nothing real to preview
    // yet (its card's iframe just hits the in-progress placeholder page).
    `SELECT o.owner, o.repo, p.description, p.language, p.avatar_url, p.created_at, p.stars
     FROM owner_repo_jobs o
     JOIN projects p
       ON LOWER(p.owner) = LOWER(o.owner) AND LOWER(p.repo) = LOWER(o.repo)
       AND p.user_login = o.owner_login
     WHERE o.visibility = 'public' AND p.status = 'done'
     ORDER BY p.created_at DESC
     LIMIT 60`,
  ).all<{
    owner: string;
    repo: string;
    description: string | null;
    language: string | null;
    avatar_url: string | null;
    created_at: number;
    stars: number | null;
  }>();

  // owner_repo_jobs is unique on (owner, repo) case-SENSITIVELY, so the same
  // repository reached under a differently-cased owner gets a second row —
  // production was serving both "Pranav322/youtube-notes" and
  // "pranav322/youtube-notes" as separate gallery cards pointing at the same
  // site. The rows are already ordered created_at DESC, so the first spelling
  // seen is the newest generation; keep that one.
  const seen = new Set<string>();
  const examples: Example[] = [];
  for (const row of results) {
    const key = `${row.owner.toLowerCase()}/${row.repo.toLowerCase()}`;
    if (seen.has(key)) continue;
    seen.add(key);
    examples.push({
      owner: row.owner,
      repo: row.repo,
      description: row.description,
      language: row.language,
      avatarUrl: row.avatar_url,
      createdAt: row.created_at,
      stars: row.stars,
    });
  }

  return new Response(JSON.stringify({ examples }), {
    headers: { "Content-Type": "application/json" },
  });
};
