"""AI Doc Planner — the brain of CodeWiki.

Phase 1: Scan repo (no LLM) → file tree, symbols, endpoints, OpenAPI specs
Phase 2: Send scan to LLM → get back a full doc plan:
    - What pages to create (title, type, description)
    - Which source files feed into each page
    - Sidebar/nav structure
    - Files that can be skipped
Phase 3: Validate coverage — ensure no important files are orphaned

This replaces the hardcoded pipeline. The AI decides everything.
"""

from __future__ import annotations

import json
import os
import fnmatch
from collections import defaultdict
from dataclasses import dataclass, field, asdict
from pathlib import Path
from typing import Any

from rich.console import Console
from rich.panel import Panel
from rich.progress import Progress, SpinnerColumn, TextColumn, BarColumn, TaskProgressColumn
from rich.table import Table

from .llm import LLMClient
from .parser import parse_file, supported_extensions
from .parser.base import ParsedFile
from .parser.api_detector import detect_endpoints, APIEndpoint

console = Console()


# ─────────────────────────────────────────────────────────────────────────────
# Data structures
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class DocPage:
    """A single page in the planned documentation."""
    title: str
    slug: str                       # filename: "authentication.md"
    page_type: str                  # overview | guide | api_reference | module | architecture | setup | integration
    description: str                # what this page covers
    source_files: list[str]         # which repo files to scan for this page
    section: str = ""               # nav section: "Getting Started", "API Reference", etc.
    priority: int = 0               # generation order (lower = first)
    depends_on: list[str] = field(default_factory=list)  # other page slugs this depends on


@dataclass
class DocPlan:
    """Complete doc plan generated by the AI."""
    pages: list[DocPage]
    nav_structure: dict[str, list[str]]     # section_name → [slug, slug, ...]
    skipped_files: list[str]                # files AI decided to skip
    orphaned_files: list[str] = field(default_factory=list)  # important files not assigned to any page


@dataclass
class RepoScan:
    """Output of the scan phase — everything we know about the repo before calling the LLM."""
    file_tree: dict[str, list[str]]         # dir → [filenames]
    file_summaries: dict[str, str]          # rel_path → short summary (symbols, imports)
    api_endpoints: list[dict]               # serialized APIEndpoints
    languages: dict[str, int]               # language → file count
    has_openapi: bool
    openapi_paths: list[str]
    total_files: int
    frameworks_detected: list[str]          # express, fastapi, laravel, gin, etc.
    entry_points: list[str]                 # main.py, index.ts, app.go, etc.
    config_files: list[str]                 # Dockerfile, docker-compose, .env.example, etc.


# ─────────────────────────────────────────────────────────────────────────────
# Scan phase (no LLM)
# ─────────────────────────────────────────────────────────────────────────────

ENTRY_POINT_NAMES = {
    "main.py", "app.py", "server.py", "manage.py", "wsgi.py", "asgi.py",
    "index.ts", "index.js", "server.ts", "server.js", "app.ts", "app.js",
    "main.go", "cmd", "main.ts", "main.js",
    "artisan", "index.php",
}

CONFIG_FILE_PATTERNS = {
    "Dockerfile", "docker-compose.yml", "docker-compose.yaml",
    ".env.example", ".env.sample",
    "Makefile", "Taskfile.yml",
    "package.json", "tsconfig.json", "pyproject.toml", "setup.py", "setup.cfg",
    "go.mod", "composer.json",
    ".github", "Procfile", "vercel.json", "netlify.toml",
    "nginx.conf", "supervisord.conf",
}

FRAMEWORK_INDICATORS = {
    "express": ["express()", "require('express')", "from 'express'"],
    "fastify": ["fastify()", "require('fastify')", "from 'fastify'"],
    "nestjs": ["@nestjs/", "@Controller", "@Injectable"],
    "nextjs": ["next.config", "getServerSideProps", "getStaticProps"],
    "fastapi": ["from fastapi", "FastAPI()"],
    "flask": ["from flask", "Flask(__name__)"],
    "django": ["django.conf", "urlpatterns", "INSTALLED_APPS"],
    "laravel": ["Route::", "Illuminate\\", "artisan"],
    "gin": ["gin.Default()", "gin.New()", "gin.Engine"],
    "echo": ["echo.New()", "echo.Echo"],
    "fiber": ["fiber.New()", "fiber.App"],
    "falcon": ["falcon.App", "falcon.API"],
}


def scan_repo(repo_root: Path, cfg: dict[str, Any]) -> RepoScan:
    """Scan the entire repo without making any LLM calls."""
    exclude = cfg.get("exclude", [])
    include = cfg.get("include", [])
    extensions = supported_extensions()

    file_tree: dict[str, list[str]] = defaultdict(list)
    file_summaries: dict[str, str] = {}
    api_endpoints: list[dict] = []
    lang_counts: dict[str, int] = defaultdict(int)
    frameworks: set[str] = set()
    entry_points: list[str] = []
    config_files: list[str] = []
    openapi_paths: list[str] = []
    all_content_cache: dict[str, str] = {}

    ext_to_lang = {
        ".py": "python", ".js": "javascript", ".jsx": "javascript",
        ".ts": "typescript", ".tsx": "typescript",
        ".go": "go", ".php": "php",
        ".mjs": "javascript", ".cjs": "javascript",
    }

    # First pass: collect all files to get total count for progress bar
    all_files_to_scan: list[Path] = []
    for root, dirs, files in os.walk(repo_root):
        root_path = Path(root)
        dirs[:] = [d for d in dirs if not _matches_any(d, exclude)]
        for fname in sorted(files):
            fpath = root_path / fname
            rel = str(fpath.relative_to(repo_root))
            if not _matches_any(rel, exclude) and not _matches_any(fname, exclude):
                all_files_to_scan.append(fpath)

    with Progress(
        SpinnerColumn(),
        TextColumn("[progress.description]{task.description}"),
        BarColumn(),
        TaskProgressColumn(),
        console=console,
        transient=True,   # clears the bar when done
    ) as progress:
        task = progress.add_task("[dim]Scanning files...[/dim]", total=len(all_files_to_scan))

        for fpath in all_files_to_scan:
            root_path = fpath.parent
            fname = fpath.name
            rel = str(fpath.relative_to(repo_root))
            rel_dir = str(root_path.relative_to(repo_root)) if root_path != repo_root else "."

            progress.update(task, description=f"[dim]Scanning {rel}[/dim]")

            # Detect config files
            if fname in CONFIG_FILE_PATTERNS or any(p in rel for p in CONFIG_FILE_PATTERNS):
                config_files.append(rel)

            # Detect OpenAPI/Swagger specs
            if fname.lower() in ("openapi.json", "openapi.yaml", "openapi.yml",
                                  "swagger.json", "swagger.yaml", "swagger.yml"):
                openapi_paths.append(rel)

            # Only parse supported source files
            if fpath.suffix.lower() not in extensions:
                file_tree[rel_dir].append(fname)
                progress.advance(task)
                continue

            if include and not _matches_any(rel, include):
                progress.advance(task)
                continue

            file_tree[rel_dir].append(fname)

            lang = ext_to_lang.get(fpath.suffix.lower(), "")
            if lang:
                lang_counts[lang] += 1

            # Detect entry points
            if fname.lower() in ENTRY_POINT_NAMES or fname.lower().rstrip(".py.ts.js.go.php") in {"main", "app", "server", "index"}:
                entry_points.append(rel)

            # Parse file for summary
            try:
                content = fpath.read_text(encoding="utf-8", errors="replace")
                all_content_cache[rel] = content
            except Exception:
                progress.advance(task)
                continue

            # Detect frameworks
            for fw, indicators in FRAMEWORK_INDICATORS.items():
                if any(ind in content for ind in indicators):
                    frameworks.add(fw)

            # Parse symbols
            parsed = parse_file(fpath)
            if parsed:
                summary_parts = []
                if parsed.symbols:
                    sym_names = [f"{s.kind}:{s.name}" for s in parsed.symbols[:15]]
                    summary_parts.append(f"symbols=[{', '.join(sym_names)}]")
                if parsed.imports:
                    summary_parts.append(f"imports={len(parsed.imports)}")
                loc = len(content.splitlines())
                summary_parts.append(f"lines={loc}")
                file_summaries[rel] = " | ".join(summary_parts)

            # Detect API endpoints
            if lang:
                eps = detect_endpoints(fpath, content, lang)
                for ep in eps:
                    api_endpoints.append({
                        "method": ep.method,
                        "path": ep.path,
                        "handler": ep.handler,
                        "file": rel,
                        "line": ep.line,
                    })

            progress.advance(task)

    return RepoScan(
        file_tree=dict(file_tree),
        file_summaries=file_summaries,
        api_endpoints=api_endpoints,
        languages=dict(lang_counts),
        has_openapi=len(openapi_paths) > 0,
        openapi_paths=openapi_paths,
        total_files=sum(len(files) for files in file_tree.values()),
        frameworks_detected=sorted(frameworks),
        entry_points=entry_points,
        config_files=config_files,
    )


# ─────────────────────────────────────────────────────────────────────────────
# Planning phase (1 LLM call)
# ─────────────────────────────────────────────────────────────────────────────

PLANNER_SYSTEM = """\
You are a senior documentation architect. Given a scan of a software repository, \
you design the complete documentation structure.

You MUST respond with valid JSON only — no markdown, no explanation, just the JSON object.

Rules:
- Design docs from a developer's perspective — what would a new dev need to onboard?
- Group related files into logical doc pages (NOT one page per file)
- YOU decide the full page structure, section names, and navigation — adapt it to the repo
- Every source file in src/, api/, app/, lib/, pkg/, internal/, cmd/ MUST be assigned to at least one page — do NOT skip them
- The ONLY files you should skip are: test files, pure type definitions with no logic, auto-generated files, and test fixtures/mocks
- NEVER skip: middleware, routes, models, services, controllers, utils, validators, error handlers, database schemas — these are all important
- API endpoints should be grouped by resource/domain, not by file
- If OpenAPI spec exists, create a dedicated API reference page that uses it
- Order pages logically: overview first, then however you think makes sense for this specific repo
- When in doubt, INCLUDE a file rather than skip it
- BE COMPREHENSIVE: Create as many pages as the codebase needs. Every important area, \
  feature, integration, and system component should have its own page. Prefer thorough \
  coverage over artificial consolidation.
- CROSS-LINKING: Pages will be generated with awareness of each other. \
  Design pages so they have clear dependencies — services depend on models, \
  controllers depend on services, etc. These dependencies drive cross-page links.
"""

PLANNER_PROMPT = """\
Design the complete documentation structure for this repository.

## Repository Overview
- **Languages**: {languages}
- **Frameworks detected**: {frameworks}
- **Total source files**: {total_files}
- **API endpoints found**: {endpoint_count}
- **OpenAPI spec**: {openapi_status}
- **Entry points**: {entry_points}
- **Config files**: {config_files}

## IMPORTANT CONSTRAINTS
- {max_pages_instruction}
- **Context per page**: Each page will receive up to 60,000 characters of source context. \
  Create as many pages as the codebase needs for thorough coverage.
- **Design for linking**: Plan pages so they have clear dependency relationships \
  (e.g. "Auth Module" depends on "Database Models") — these become cross-page links.

## Directory Structure (compressed)
{file_tree}

## File Summaries by Directory
{file_summaries}

## API Endpoints Detected
{endpoints}

---

Return a JSON object with this exact structure:
{{
  "pages": [
    {{
      "title": "Page Title",
      "slug": "page-slug",
      "page_type": "overview|guide|api_reference|module|architecture|setup|integration|deployment",
      "description": "What this page covers",
      "source_files": ["src/auth/login.ts", "src/auth/middleware.ts"],
      "section": "Section Name for sidebar",
      "priority": 0
    }}
  ],
  "nav_structure": {{
    "Getting Started": ["overview", "setup"],
    "Architecture": ["architecture"],
    "Core Modules": ["users-module", "orders-module"],
    "API Reference": ["users-api", "orders-api"],
    "Deployment": ["deployment"]
  }},
  "skipped_files": ["src/utils/helpers.ts", "src/types/index.d.ts"]
}}

Important:
- page_type must be one of: overview, guide, api_reference, module, architecture, setup, integration, deployment
- source_files must be actual file paths from the directory structure above
- EVERY source file under src/, api/, app/, lib/ MUST appear in at least one page's source_files
- slug must be unique, kebab-case, and suitable as a filename (no spaces or special chars)
- section names in nav_structure should be human-readable
- priority: 0 = generate first, higher = later
- For api_reference pages: group endpoints by resource (users, orders, products, etc.)
- skipped_files should be VERY small — only test files and auto-generated files
- If you're unsure whether to skip a file, DO NOT skip it — assign it to the most relevant page
- {max_pages_instruction}
"""


def plan_docs(scan: RepoScan, cfg: dict[str, Any], llm: LLMClient) -> DocPlan:
    """Send scan results to LLM and get back a doc plan."""
    from rich.live import Live
    from rich.spinner import Spinner
    from rich.text import Text

    max_pages = cfg.get("max_pages", 0)

    # Build max_pages instruction
    if max_pages and max_pages > 0:
        max_pages_instruction = f"Maximum pages: {max_pages} — do not exceed this. Consolidate if needed."
    else:
        max_pages_instruction = (
            "No hard limit on page count. Create as many pages as needed for "
            "thorough, deep documentation. Completeness matters most."
        )

    # Build prompt context — compressed formats fit 300+ files within limits
    file_tree_str = _format_file_tree_compressed(scan.file_tree, scan.file_summaries)
    file_summaries_str = _format_summaries_compressed(scan.file_summaries)
    endpoints_str = _format_endpoints(scan.api_endpoints)

    prompt = PLANNER_PROMPT.format(
        languages=", ".join(f"{lang} ({count})" for lang, count in sorted(scan.languages.items(), key=lambda x: -x[1])),
        frameworks=", ".join(scan.frameworks_detected) or "none detected",
        total_files=scan.total_files,
        endpoint_count=len(scan.api_endpoints),
        openapi_status=f"yes ({', '.join(scan.openapi_paths)})" if scan.has_openapi else "none found",
        entry_points=", ".join(scan.entry_points[:10]) or "none detected",
        config_files=", ".join(scan.config_files[:15]) or "none",
        max_pages_instruction=max_pages_instruction,
        file_tree=file_tree_str[:15000],
        file_summaries=file_summaries_str[:20000],
        endpoints=endpoints_str[:5000],
    )

    response = None
    error = None

    # Show a live spinner while the LLM thinks (can take 15-30s)
    with Live(
        Text("⠋ Asking AI to plan doc structure... (this may take 15-30s)", style="bold cyan"),
        console=console,
        refresh_per_second=10,
        transient=True,
    ):
        try:
            response = llm.complete(PLANNER_SYSTEM, prompt)
        except Exception as e:
            error = e

    if error:
        console.print(f"[yellow]⚠ AI planner failed: {error}[/yellow]")
        console.print("[dim]Falling back to auto-generated plan...[/dim]")
        plan = _fallback_plan(scan)
    else:
        try:
            plan = _parse_plan_response(response, scan)
            console.print("[green]✓[/green] AI doc plan received")
        except Exception as e:
            console.print(f"[yellow]⚠ Could not parse AI plan ({e}) — using auto-plan[/yellow]")
            plan = _fallback_plan(scan)

    # Validate coverage
    console.print("[dim]Validating file coverage...[/dim]")
    plan = _validate_coverage(plan, scan)
    if plan.orphaned_files:
        console.print(f"[yellow]⚠ {len(plan.orphaned_files)} file(s) were unassigned → auto-assigned to nearest section[/yellow]")

    # Ensure API reference page exists if endpoints were detected
    plan = _ensure_api_reference(plan, scan)

    # Remove test/coverage pages — tests shouldn't be documented
    plan = _remove_test_pages(plan)

    _print_plan_summary(plan)
    return plan


def _parse_plan_response(response: str, scan: RepoScan) -> DocPlan:
    """Parse LLM JSON response into a DocPlan."""
    # Extract JSON from response (handle markdown code blocks)
    json_str = response.strip()
    if json_str.startswith("```"):
        lines = json_str.splitlines()
        # Remove first and last ``` lines
        lines = [l for l in lines if not l.strip().startswith("```")]
        json_str = "\n".join(lines)

    data = json.loads(json_str)

    pages = []
    for p in data.get("pages", []):
        pages.append(DocPage(
            title=p["title"],
            slug=p["slug"],
            page_type=p.get("page_type", "guide"),
            description=p.get("description", ""),
            source_files=p.get("source_files", []),
            section=p.get("section", ""),
            priority=p.get("priority", 0),
            depends_on=p.get("depends_on", []),
        ))

    return DocPlan(
        pages=sorted(pages, key=lambda p: p.priority),
        nav_structure=data.get("nav_structure", {}),
        skipped_files=data.get("skipped_files", []),
    )


def _validate_coverage(plan: DocPlan, scan: RepoScan) -> DocPlan:
    """Ensure all important files are assigned to at least one page.
    Files not in any page and not in skipped_files → orphaned."""
    all_assigned: set[str] = set()
    for page in plan.pages:
        all_assigned.update(page.source_files)
    skipped = set(plan.skipped_files)

    all_source_files = set(scan.file_summaries.keys())
    orphaned = all_source_files - all_assigned - skipped

    if orphaned:
        # Group orphaned files by directory and add them to the closest existing page
        # or create a "Miscellaneous" page
        orphan_groups: dict[str, list[str]] = defaultdict(list)
        for f in orphaned:
            parts = f.split("/")
            group = parts[0] if len(parts) > 1 else "root"
            orphan_groups[group].append(f)

        for group_name, files in orphan_groups.items():
            # Try to find an existing page that covers this directory
            matched = False
            for page in plan.pages:
                if any(f.startswith(group_name + "/") for f in page.source_files):
                    page.source_files.extend(files)
                    matched = True
                    break

            if not matched:
                # Create a catch-all page for this group
                plan.pages.append(DocPage(
                    title=f"{group_name.replace('_', ' ').replace('-', ' ').title()} Module",
                    slug=f"{group_name.lower().replace(' ', '-')}-module",
                    page_type="module",
                    description=f"Documentation for {group_name}/ directory",
                    source_files=files,
                    section="Modules",
                    priority=50,
                ))

        plan.orphaned_files = sorted(orphaned)

    return plan


def _ensure_api_reference(plan: DocPlan, scan: RepoScan) -> DocPlan:
    """If API endpoints were detected but no api_reference page exists, create one.

    This runs AFTER the AI plan or fallback — it's a safety net, not a replacement
    for the AI's judgment. The AI decides all other pages freely; this just ensures
    endpoints don't get silently lost.
    """
    import re

    if not scan.api_endpoints:
        return plan

    # Check if any api_reference page already exists
    has_api_page = any(p.page_type == "api_reference" for p in plan.pages)
    if has_api_page:
        return plan

    console.print("[yellow]⚠ Endpoints detected but no API reference page in plan — adding one[/yellow]")

    # Collect all route/endpoint source files
    endpoint_files = sorted(set(ep["file"] for ep in scan.api_endpoints))

    # Group by resource for the description
    resource_groups: dict[str, list[dict]] = defaultdict(list)
    for ep in scan.api_endpoints:
        path = ep.get("path", "")
        clean = re.sub(r"^/(?:api/)?(?:v\d+/)?", "", path)
        parts = [p for p in clean.split("/") if p and not p.startswith(":") and not p.startswith("{")]
        resource = parts[0] if parts else "general"
        resource_groups[resource].append(ep)

    desc = f"Complete API reference — {len(scan.api_endpoints)} endpoints across {len(resource_groups)} resources: {', '.join(sorted(resource_groups.keys()))}"

    plan.pages.append(DocPage(
        title="API Reference",
        slug="api-reference",
        page_type="api_reference",
        description=desc,
        source_files=endpoint_files,
        section="API Reference",
        priority=20,
    ))

    # Add to nav
    if "API Reference" not in plan.nav_structure:
        plan.nav_structure["API Reference"] = []
    plan.nav_structure["API Reference"].append("api-reference")

    return plan


def _remove_test_pages(plan: DocPlan) -> DocPlan:
    """Remove pages that only document test files — tests don't need docs."""
    test_indicators = ("test", "tests", "spec", "coverage", "__tests__")

    pages_to_keep = []
    slugs_to_remove = set()

    for page in plan.pages:
        slug_lower = page.slug.lower()
        # Remove if the slug itself is a test page
        is_test_page = any(t in slug_lower for t in test_indicators)
        # Also check if ALL source files are test files
        all_test_files = page.source_files and all(
            any(t in f.split("/") for t in test_indicators) or f.startswith("coverage/")
            for f in page.source_files
        )

        if is_test_page or all_test_files:
            slugs_to_remove.add(page.slug)
        else:
            pages_to_keep.append(page)

    if slugs_to_remove:
        console.print(f"[dim]Removed {len(slugs_to_remove)} test/coverage page(s): {', '.join(sorted(slugs_to_remove))}[/dim]")
        plan.pages = pages_to_keep
        # Clean nav
        for section in list(plan.nav_structure.keys()):
            plan.nav_structure[section] = [
                s for s in plan.nav_structure[section] if s not in slugs_to_remove
            ]
            if not plan.nav_structure[section]:
                del plan.nav_structure[section]

    return plan


# ─────────────────────────────────────────────────────────────────────────────
# Fallback plan (if LLM fails)
# ─────────────────────────────────────────────────────────────────────────────

def _fallback_plan(scan: RepoScan) -> DocPlan:
    """Generate a reasonable doc plan without LLM, based on repo structure.

    Smarter grouping:
    - Groups files by logical domain (2nd-level dirs under src/)
    - Creates dedicated pages for middleware, models, utils, routes
    - Merges API endpoints by resource instead of per-file
    - Only skips test files and non-source files
    """
    import re

    pages: list[DocPage] = []
    nav: dict[str, list[str]] = defaultdict(list)
    assigned_files: set[str] = set()

    # ── Overview ──────────────────────────────────────────────────────────
    overview_files = scan.entry_points[:5] + scan.config_files[:3]
    pages.append(DocPage(
        title="Overview",
        slug="overview",
        page_type="overview",
        description="Project overview, purpose, and high-level architecture",
        source_files=overview_files,
        section="Getting Started",
        priority=0,
    ))
    nav["Getting Started"].append("overview")
    assigned_files.update(overview_files)

    # ── Setup page ────────────────────────────────────────────────────────
    if scan.config_files:
        pages.append(DocPage(
            title="Setup & Configuration",
            slug="setup",
            page_type="setup",
            description="Installation, environment variables, and configuration",
            source_files=scan.config_files[:10],
            section="Getting Started",
            priority=1,
        ))
        nav["Getting Started"].append("setup")
        assigned_files.update(scan.config_files[:10])

    # ── Categorize all source files by role ────────────────────────────────
    # Detect well-known directory roles
    role_buckets: dict[str, list[str]] = defaultdict(list)
    domain_buckets: dict[str, list[str]] = defaultdict(list)

    ROLE_DIRS = {
        "middleware": ["middleware", "middlewares"],
        "models": ["model", "models", "schemas", "entities"],
        "routes": ["route", "routes", "router", "routers"],
        "controllers": ["controller", "controllers", "handlers"],
        "services": ["service", "services"],
        "utils": ["util", "utils", "helpers", "lib", "common"],
        "config": ["config", "configs", "settings"],
    }

    # Build reverse lookup: dir_name → role
    dir_to_role: dict[str, str] = {}
    for role, dir_names in ROLE_DIRS.items():
        for d in dir_names:
            dir_to_role[d] = role

    for rel_path in scan.file_summaries:
        parts = rel_path.split("/")

        # Skip test files from main doc pages (they'll get their own page)
        if any(p in ("tests", "test", "__tests__", "spec") for p in parts):
            continue

        # Check if any path component matches a known role
        matched_role = None
        for part in parts:
            if part.lower() in dir_to_role:
                matched_role = dir_to_role[part.lower()]
                break

        if matched_role:
            role_buckets[matched_role].append(rel_path)
        else:
            # Group by 2nd-level dir under src/ (or top-level otherwise)
            if len(parts) >= 3 and parts[0] in ("src", "api", "app", "pkg", "internal"):
                group = parts[1]
            elif len(parts) >= 2:
                group = parts[0]
            else:
                group = "root"
            domain_buckets[group].append(rel_path)

    # ── Architecture page ─────────────────────────────────────────────────
    arch_files = (
        role_buckets.get("config", [])[:5] +
        scan.entry_points[:3] +
        role_buckets.get("routes", [])[:3]
    )
    if arch_files:
        pages.append(DocPage(
            title="System Architecture",
            slug="architecture",
            page_type="architecture",
            description="System design, request flow, component interactions, and data flow",
            source_files=arch_files,
            section="Architecture",
            priority=2,
        ))
        nav["Architecture"].append("architecture")
        assigned_files.update(arch_files)

    # ── Middleware page ────────────────────────────────────────────────────
    mw_files = role_buckets.get("middleware", [])
    if mw_files:
        pages.append(DocPage(
            title="Middleware & Cross-Cutting Concerns",
            slug="middleware",
            page_type="module",
            description="Authentication, rate limiting, validation, error handling, and other middleware",
            source_files=mw_files,
            section="Core Modules",
            priority=5,
        ))
        nav["Core Modules"].append("middleware")
        assigned_files.update(mw_files)

    # ── Database & Models page ────────────────────────────────────────────
    model_files = role_buckets.get("models", [])
    if model_files:
        pages.append(DocPage(
            title="Database & Models",
            slug="database-models",
            page_type="module",
            description="Database schemas, models, and data access layer",
            source_files=model_files,
            section="Core Modules",
            priority=6,
        ))
        nav["Core Modules"].append("database-models")
        assigned_files.update(model_files)

    # ── Services page (if large enough, otherwise merge into domain pages)
    svc_files = role_buckets.get("services", [])
    if len(svc_files) >= 3:
        pages.append(DocPage(
            title="Business Logic & Services",
            slug="services",
            page_type="module",
            description="Core business logic, service layer, and domain operations",
            source_files=svc_files,
            section="Core Modules",
            priority=7,
        ))
        nav["Core Modules"].append("services")
        assigned_files.update(svc_files)

    # ── Controllers page (if separate from routes) ────────────────────────
    ctrl_files = role_buckets.get("controllers", [])
    if ctrl_files:
        pages.append(DocPage(
            title="Controllers",
            slug="controllers",
            page_type="module",
            description="Request handlers and controller logic",
            source_files=ctrl_files,
            section="Core Modules",
            priority=8,
        ))
        nav["Core Modules"].append("controllers")
        assigned_files.update(ctrl_files)

    # ── Utilities page ────────────────────────────────────────────────────
    util_files = role_buckets.get("utils", [])
    if util_files:
        pages.append(DocPage(
            title="Utilities & Helpers",
            slug="utilities",
            page_type="module",
            description="Shared utilities, helper functions, logging, error handling, and common libraries",
            source_files=util_files,
            section="Core Modules",
            priority=9,
        ))
        nav["Core Modules"].append("utilities")
        assigned_files.update(util_files)

    # ── Domain module pages (remaining groups) ────────────────────────────
    for group_name, files in sorted(domain_buckets.items()):
        if group_name in (".", "root") and len(files) <= 2:
            # Add root files to overview instead of creating a tiny page
            pages[0].source_files.extend(files)
            assigned_files.update(files)
            continue
        slug = f"{group_name.lower().replace(' ', '-').replace('_', '-')}-module"
        pages.append(DocPage(
            title=f"{group_name.replace('_', ' ').replace('-', ' ').title()} Module",
            slug=slug,
            page_type="module",
            description=f"Documentation for the {group_name} module",
            source_files=files,
            section="Modules",
            priority=10,
        ))
        nav["Modules"].append(slug)
        assigned_files.update(files)

    # ── Services that weren't big enough for their own page → merge ──────
    if len(svc_files) < 3 and svc_files:
        # Add to the first module page or create one
        if nav.get("Core Modules"):
            for p in pages:
                if p.slug in nav["Core Modules"]:
                    p.source_files.extend(svc_files)
                    assigned_files.update(svc_files)
                    break
        else:
            pages.append(DocPage(
                title="Core Services",
                slug="services",
                page_type="module",
                description="Business logic and service layer",
                source_files=svc_files,
                section="Core Modules",
                priority=7,
            ))
            nav["Core Modules"].append("services")
            assigned_files.update(svc_files)

    # ── API Reference (grouped by resource) ───────────────────────────────
    if scan.api_endpoints:
        # Group endpoints by resource name
        resource_groups: dict[str, list[dict]] = defaultdict(list)
        for ep in scan.api_endpoints:
            path = ep.get("path", "")
            clean = re.sub(r"^/(?:api/)?(?:v\d+/)?", "", path)
            parts_list = [p for p in clean.split("/") if p and not p.startswith(":") and not p.startswith("{")]
            resource = parts_list[0] if parts_list else "general"
            resource_groups[resource].append(ep)

        # If few resources, create one combined API page; otherwise per-resource
        if len(resource_groups) <= 4:
            all_api_files = sorted(set(ep["file"] for ep in scan.api_endpoints))
            route_files = role_buckets.get("routes", [])
            combined_files = sorted(set(all_api_files + route_files))
            pages.append(DocPage(
                title="API Reference",
                slug="api-reference",
                page_type="api_reference",
                description=f"Complete API reference — {len(scan.api_endpoints)} endpoints across {len(resource_groups)} resources",
                source_files=combined_files,
                section="API Reference",
                priority=20,
            ))
            nav["API Reference"].append("api-reference")
            assigned_files.update(combined_files)
        else:
            for resource, eps in sorted(resource_groups.items()):
                source_files = sorted(set(ep["file"] for ep in eps))
                slug = f"{resource}-api"
                pages.append(DocPage(
                    title=f"{resource.replace('_', ' ').replace('-', ' ').title()} API",
                    slug=slug,
                    page_type="api_reference",
                    description=f"API reference for {resource} endpoints ({len(eps)} endpoints)",
                    source_files=source_files,
                    section="API Reference",
                    priority=20,
                ))
                nav["API Reference"].append(slug)
                assigned_files.update(source_files)

    # ── Routes registry (if not already assigned) ─────────────────────────
    route_files = role_buckets.get("routes", [])
    unassigned_routes = [f for f in route_files if f not in assigned_files]
    if unassigned_routes:
        # Add to API reference page if it exists, otherwise to architecture
        api_pages = [p for p in pages if p.page_type == "api_reference"]
        if api_pages:
            api_pages[0].source_files.extend(unassigned_routes)
        else:
            arch_pages = [p for p in pages if p.page_type == "architecture"]
            if arch_pages:
                arch_pages[0].source_files.extend(unassigned_routes)
        assigned_files.update(unassigned_routes)

    # ── Skip only test files and truly non-important files ───────────────
    all_source = set(scan.file_summaries.keys())
    test_files = set(f for f in all_source if any(
        p in f.split("/") for p in ("tests", "test", "__tests__", "spec")
    ))
    skipped = test_files | (all_source - assigned_files - test_files)
    # Any unassigned non-test files should go through coverage validation, not skip
    skip_list = sorted(test_files)

    return DocPlan(
        pages=pages,
        nav_structure=dict(nav),
        skipped_files=skip_list,
    )


# ─────────────────────────────────────────────────────────────────────────────
# Formatting helpers — compressed to fit 300+ file repos in planner context
# ─────────────────────────────────────────────────────────────────────────────

def _format_file_tree_compressed(tree: dict[str, list[str]], summaries: dict[str, str]) -> str:
    """Compress file tree to directory-level summaries so 300+ files fit.

    Format per directory:
      src/auth/ (6 files: auth.ts, middleware.ts, tokens.ts, +3 more)
        Key symbols: verifyToken, AuthMiddleware, generateJWT, RefreshToken
    """
    lines = []
    for dir_path in sorted(tree.keys()):
        files = tree[dir_path]
        if not files:
            continue

        # Count by extension
        ext_counts: dict[str, int] = defaultdict(int)
        for f in files:
            ext = f.rsplit(".", 1)[-1] if "." in f else "other"
            ext_counts[ext] += 1

        ext_summary = ", ".join(f"{count} .{ext}" for ext, count in sorted(ext_counts.items(), key=lambda x: -x[1]))
        shown = sorted(files)[:5]
        rest = len(files) - len(shown)
        file_list = ", ".join(shown) + (f", +{rest} more" if rest > 0 else "")

        lines.append(f"\n{dir_path}/ ({len(files)} files: {ext_summary})")
        lines.append(f"  Files: {file_list}")

        # Collect top symbols from this directory's files
        all_symbols: list[str] = []
        for rel_path, summary in summaries.items():
            file_dir = "/".join(rel_path.split("/")[:-1]) if "/" in rel_path else "."
            if file_dir == dir_path and "symbols=[" in summary:
                try:
                    sym_part = summary.split("symbols=[")[1].split("]")[0]
                    # Extract just the names (strip the kind: prefix)
                    names = [s.split(":")[-1].strip() for s in sym_part.split(",") if ":" in s]
                    all_symbols.extend(names[:5])
                except Exception:
                    pass

        if all_symbols:
            lines.append(f"  Key symbols: {', '.join(all_symbols[:12])}")

    return "\n".join(lines)


def _format_summaries_compressed(summaries: dict[str, str]) -> str:
    """Compressed per-file summaries grouped by directory.

    Each line: path (Nlines) — symbol1, symbol2, ...
    """
    lines: list[str] = []
    for path in sorted(summaries.keys()):
        summary = summaries[path]
        # Extract line count
        line_count = ""
        if "lines=" in summary:
            try:
                line_count = summary.split("lines=")[-1].split("|")[0].strip()
                line_count = f" ({line_count}L)"
            except Exception:
                pass
        # Extract symbol names (compact)
        symbols = ""
        if "symbols=[" in summary:
            try:
                sym_part = summary.split("symbols=[")[1].split("]")[0]
                names = [s.split(":")[-1].strip() for s in sym_part.split(",") if ":" in s]
                if names:
                    symbols = f" → {', '.join(names[:8])}"
                    if len(names) > 8:
                        symbols += f" +{len(names) - 8}"
            except Exception:
                pass
        lines.append(f"- {path}{line_count}{symbols}")
    return "\n".join(lines)


def _format_endpoints(endpoints: list[dict]) -> str:
    if not endpoints:
        return "(none)"
    lines = []
    for ep in endpoints[:50]:
        lines.append(f"- {ep['method']} {ep['path']} → {ep.get('handler', '?')} ({ep.get('file', '')}:{ep.get('line', 0)})")
    if len(endpoints) > 50:
        lines.append(f"... +{len(endpoints) - 50} more endpoints")
    return "\n".join(lines)


def _print_plan_summary(plan: DocPlan) -> None:
    table = Table(title="Documentation Plan", show_header=True, header_style="bold")
    table.add_column("#", style="dim", width=3)
    table.add_column("Page", style="cyan")
    table.add_column("Type", style="green")
    table.add_column("Section")
    table.add_column("Files", justify="right")

    for i, page in enumerate(plan.pages, 1):
        table.add_row(
            str(i),
            page.title,
            page.page_type,
            page.section,
            str(len(page.source_files)),
        )

    console.print(table)

    total_files = sum(len(p.source_files) for p in plan.pages)
    console.print(
        f"\n[dim]{len(plan.pages)} doc pages covering {total_files} source files | "
        f"{len(plan.skipped_files)} files skipped"
        f"{f' | {len(plan.orphaned_files)} orphaned → auto-assigned' if plan.orphaned_files else ''}[/dim]"
    )


def _matches_any(path: str, patterns: list[str]) -> bool:
    for pattern in patterns:
        if fnmatch.fnmatch(path, pattern) or fnmatch.fnmatch(os.path.basename(path), pattern) or pattern in path.split(os.sep):
            return True
    return False
