"""V2 Multi-Step Planner — Bucket-Based Documentation Architecture.

Three-step planning pipeline:
  Step 1: CLASSIFY — categorize repo artifacts into source, setup, test, deploy,
          integration candidates, and cross-cutting/system areas
  Step 2: PROPOSE — create bucket candidates across system, feature, endpoint,
          and integration types
  Step 3: ASSIGN — map files/symbols/artifacts to buckets, produce final page plan

Four bucket types:
  - system:      architecture, setup, testing, deployment/ops, auth/middleware,
                 database layer, observability, shared cross-cutting concerns
  - feature:     business workflows (checkout, cancel/refund, order status, etc.)
  - endpoint:    endpoint or endpoint-family documentation
  - integration: external systems (Vinculum, Juspay, delivery partners, etc.)
"""

from __future__ import annotations

import json
import os
import fnmatch
from collections import defaultdict
from dataclasses import dataclass, field, asdict
from pathlib import Path
from typing import Any, Literal

from rich.console import Console
from rich.panel import Panel
from rich.progress import Progress, SpinnerColumn, TextColumn, BarColumn, TaskProgressColumn
from rich.table import Table

from .llm import LLMClient
from .parser import parse_file, supported_extensions
from .parser.base import ParsedFile
from .parser.api_detector import detect_endpoints, APIEndpoint

console = Console()


# ─────────────────────────────────────────────────────────────────────────────
# Data structures
# ─────────────────────────────────────────────────────────────────────────────

BucketType = Literal["system", "feature", "endpoint", "endpoint_ref", "integration", "database"]


@dataclass
class DocBucket:
    """A single documentation bucket — the core planning unit in v2."""
    bucket_type: BucketType
    title: str
    slug: str
    section: str                           # nav section: "Architecture", "Features", etc.
    description: str
    depends_on: list[str] = field(default_factory=list)       # other bucket slugs
    owned_files: list[str] = field(default_factory=list)      # source files
    owned_symbols: list[str] = field(default_factory=list)    # "ClassName.method" or "functionName"
    artifact_refs: list[str] = field(default_factory=list)    # config, env, deploy, test files
    required_sections: list[str] = field(default_factory=list)
    required_diagrams: list[str] = field(default_factory=list)
    coverage_targets: list[str] = field(default_factory=list)  # what must be covered
    priority: int = 0


@dataclass
class DocPlan:
    """Complete doc plan generated by the multi-step planner."""
    buckets: list[DocBucket]
    nav_structure: dict[str, list[str]]     # section_name → [slug, slug, ...]
    skipped_files: list[str]
    orphaned_files: list[str] = field(default_factory=list)
    # Intermediate outputs preserved for debugging/persistence
    classification: dict[str, Any] = field(default_factory=dict)
    integration_candidates: list[dict] = field(default_factory=list)

    # Compatibility — pipeline_v2 currently reads .pages
    @property
    def pages(self) -> list[_BucketAsPage]:
        """Shim so existing pipeline_v2.py can treat buckets like pages."""
        return [_BucketAsPage(b) for b in self.buckets]


class _BucketAsPage:
    """Adapter so DocBucket looks like the old DocPage to existing code."""
    def __init__(self, bucket: DocBucket):
        self._b = bucket

    @property
    def title(self): return self._b.title
    @property
    def slug(self): return self._b.slug
    @property
    def page_type(self): return self._b.bucket_type
    @property
    def description(self): return self._b.description
    @property
    def source_files(self): return self._b.owned_files
    @source_files.setter
    def source_files(self, val): self._b.owned_files = val
    @property
    def section(self): return self._b.section
    @property
    def priority(self): return self._b.priority
    @property
    def depends_on(self): return self._b.depends_on


@dataclass
class RepoScan:
    """Output of the scan phase — everything we know about the repo before calling the LLM."""
    file_tree: dict[str, list[str]]         # dir → [filenames]
    file_summaries: dict[str, str]          # rel_path → short summary (symbols, imports)
    api_endpoints: list[dict]               # serialized APIEndpoints
    languages: dict[str, int]               # language → file count
    has_openapi: bool
    openapi_paths: list[str]
    total_files: int
    frameworks_detected: list[str]
    entry_points: list[str]
    config_files: list[str]
    # New in v2 — Phase 1
    file_line_counts: dict[str, int] = field(default_factory=dict)   # rel_path → line count
    parsed_files: dict[str, ParsedFile] = field(default_factory=dict)  # rel_path → ParsedFile
    file_contents: dict[str, str] = field(default_factory=dict)        # rel_path → content (for integration scan)
    # New in v2 — Phase 2 (populated by run_phase2_scans)
    giant_file_clusters: dict[str, Any] = field(default_factory=dict)    # file_path → GiantFileAnalysis
    endpoint_bundles: list[Any] = field(default_factory=list)            # EndpointBundle list
    integration_identities: list[Any] = field(default_factory=list)      # IntegrationIdentity list
    artifact_scan: Any = None                                            # ArtifactScan


# ─────────────────────────────────────────────────────────────────────────────
# Scan phase (no LLM) — enhanced from v1
# ─────────────────────────────────────────────────────────────────────────────

ENTRY_POINT_NAMES = {
    "main.py", "app.py", "server.py", "manage.py", "wsgi.py", "asgi.py",
    "index.ts", "index.js", "server.ts", "server.js", "app.ts", "app.js",
    "main.go", "cmd", "main.ts", "main.js",
    "artisan", "index.php",
}

CONFIG_FILE_PATTERNS = {
    "Dockerfile", "docker-compose.yml", "docker-compose.yaml",
    ".env.example", ".env.sample",
    "Makefile", "Taskfile.yml",
    "package.json", "tsconfig.json", "pyproject.toml", "setup.py", "setup.cfg",
    "go.mod", "composer.json",
    ".github", "Procfile", "vercel.json", "netlify.toml",
    "nginx.conf", "supervisord.conf",
    "requirements.txt", "requirements-dev.txt",
}

FRAMEWORK_INDICATORS = {
    "express": ["express()", "require('express')", "from 'express'"],
    "fastify": ["fastify()", "require('fastify')", "from 'fastify'"],
    "nestjs": ["@nestjs/", "@Controller", "@Injectable"],
    "nextjs": ["next.config", "getServerSideProps", "getStaticProps"],
    "fastapi": ["from fastapi", "FastAPI()"],
    "flask": ["from flask", "Flask(__name__)"],
    "django": ["django.conf", "urlpatterns", "INSTALLED_APPS"],
    "laravel": ["Route::", "Illuminate\\", "artisan"],
    "gin": ["gin.Default()", "gin.New()", "gin.Engine"],
    "echo": ["echo.New()", "echo.Echo"],
    "fiber": ["fiber.New()", "fiber.App"],
    "falcon": ["falcon.App", "falcon.API"],
}


def scan_repo(repo_root: Path, cfg: dict[str, Any]) -> RepoScan:
    """Scan the entire repo without making any LLM calls.

    Enhanced from v1: also records line counts and parsed files for
    giant-file detection and symbol-level bucket assignment.
    """
    exclude = cfg.get("exclude", [])
    include = cfg.get("include", [])
    extensions = supported_extensions()

    file_tree: dict[str, list[str]] = defaultdict(list)
    file_summaries: dict[str, str] = {}
    api_endpoints: list[dict] = []
    lang_counts: dict[str, int] = defaultdict(int)
    frameworks: set[str] = set()
    entry_points: list[str] = []
    config_files: list[str] = []
    openapi_paths: list[str] = []
    file_line_counts: dict[str, int] = {}
    parsed_files: dict[str, ParsedFile] = {}
    file_contents: dict[str, str] = {}

    ext_to_lang = {
        ".py": "python", ".js": "javascript", ".jsx": "javascript",
        ".ts": "typescript", ".tsx": "typescript",
        ".go": "go", ".php": "php",
        ".mjs": "javascript", ".cjs": "javascript",
    }

    # First pass: collect all files
    all_files_to_scan: list[Path] = []
    for root, dirs, files in os.walk(repo_root):
        root_path = Path(root)
        dirs[:] = [d for d in dirs if not _matches_any(d, exclude)]
        for fname in sorted(files):
            fpath = root_path / fname
            rel = str(fpath.relative_to(repo_root))
            if not _matches_any(rel, exclude) and not _matches_any(fname, exclude):
                all_files_to_scan.append(fpath)

    with Progress(
        SpinnerColumn(),
        TextColumn("[progress.description]{task.description}"),
        BarColumn(),
        TaskProgressColumn(),
        console=console,
        transient=True,
    ) as progress:
        task = progress.add_task("[dim]Scanning files...[/dim]", total=len(all_files_to_scan))

        for fpath in all_files_to_scan:
            fname = fpath.name
            rel = str(fpath.relative_to(repo_root))
            rel_dir = str(fpath.parent.relative_to(repo_root)) if fpath.parent != repo_root else "."

            progress.update(task, description=f"[dim]Scanning {rel}[/dim]")

            # Detect config files
            if fname in CONFIG_FILE_PATTERNS or any(p in rel for p in CONFIG_FILE_PATTERNS):
                config_files.append(rel)

            # Detect OpenAPI/Swagger specs
            if fname.lower() in ("openapi.json", "openapi.yaml", "openapi.yml",
                                  "swagger.json", "swagger.yaml", "swagger.yml"):
                openapi_paths.append(rel)

            # Only parse supported source files
            if fpath.suffix.lower() not in extensions:
                file_tree[rel_dir].append(fname)
                progress.advance(task)
                continue

            if include and not _matches_any(rel, include):
                progress.advance(task)
                continue

            file_tree[rel_dir].append(fname)

            lang = ext_to_lang.get(fpath.suffix.lower(), "")
            if lang:
                lang_counts[lang] += 1

            # Detect entry points
            if fname.lower() in ENTRY_POINT_NAMES or fname.lower().rstrip(".py.ts.js.go.php") in {"main", "app", "server", "index"}:
                entry_points.append(rel)

            # Parse file for summary
            try:
                content = fpath.read_text(encoding="utf-8", errors="replace")
                line_count = len(content.splitlines())
                file_line_counts[rel] = line_count
                file_contents[rel] = content
            except Exception:
                progress.advance(task)
                continue

            # Detect frameworks
            for fw, indicators in FRAMEWORK_INDICATORS.items():
                if any(ind in content for ind in indicators):
                    frameworks.add(fw)

            # Parse symbols
            parsed = parse_file(fpath)
            if parsed:
                parsed_files[rel] = parsed
                summary_parts = []
                if parsed.symbols:
                    sym_names = [f"{s.kind}:{s.name}" for s in parsed.symbols[:15]]
                    summary_parts.append(f"symbols=[{', '.join(sym_names)}]")
                if parsed.imports:
                    summary_parts.append(f"imports={len(parsed.imports)}")
                summary_parts.append(f"lines={line_count}")
                file_summaries[rel] = " | ".join(summary_parts)

            # Detect API endpoints
            if lang:
                eps = detect_endpoints(fpath, content, lang)
                for ep in eps:
                    api_endpoints.append({
                        "method": ep.method,
                        "path": ep.path,
                        "handler": ep.handler,
                        "file": rel,
                        "line": ep.line,
                    })

            progress.advance(task)

    return RepoScan(
        file_tree=dict(file_tree),
        file_summaries=file_summaries,
        api_endpoints=api_endpoints,
        languages=dict(lang_counts),
        has_openapi=len(openapi_paths) > 0,
        openapi_paths=openapi_paths,
        total_files=sum(len(files) for files in file_tree.values()),
        frameworks_detected=sorted(frameworks),
        entry_points=entry_points,
        config_files=config_files,
        file_line_counts=file_line_counts,
        parsed_files=parsed_files,
        file_contents=file_contents,
    )


# ─────────────────────────────────────────────────────────────────────────────
# Phase 2 Scan Upgrades — run after basic scan, before/during planning
# ─────────────────────────────────────────────────────────────────────────────

def run_phase2_scans(scan: RepoScan, cfg: dict[str, Any], llm: LLMClient) -> RepoScan:
    """Enrich the basic scan with Phase 2 capabilities.

    Runs giant-file clustering, endpoint bundle building, integration discovery,
    and artifact discovery. Mutates and returns the scan object.
    """
    from .scan_v2 import (
        cluster_giant_file,
        build_endpoint_bundles,
        discover_integrations,
        discover_artifacts,
    )

    giant_threshold = cfg.get("giant_file_lines", 2000)
    integration_mode = cfg.get("integration_detection", "auto")

    # 2.1 Giant-file clustering
    giant_files = {
        path: lc for path, lc in scan.file_line_counts.items()
        if lc >= giant_threshold and path in scan.parsed_files
    }
    if giant_files:
        console.print(f"  [bold]Clustering {len(giant_files)} giant file(s)...[/bold]")
        for path, lc in sorted(giant_files.items(), key=lambda x: -x[1]):
            console.print(f"    [dim]{path} ({lc} lines)[/dim]")
            parsed = scan.parsed_files[path]
            content = scan.file_contents.get(path, "")
            analysis = cluster_giant_file(path, parsed, content, llm)
            scan.giant_file_clusters[path] = analysis
            cluster_names = [c.cluster_name for c in analysis.clusters]
            console.print(f"    [green]✓[/green] {len(analysis.clusters)} clusters: {', '.join(cluster_names)}")

    # 2.2 Endpoint evidence bundles
    if scan.api_endpoints and cfg.get("include_endpoint_pages", True):
        console.print(f"  [bold]Building endpoint evidence bundles...[/bold]")
        scan.endpoint_bundles = build_endpoint_bundles(
            scan.api_endpoints,
            scan.parsed_files,
            scan.file_summaries,
            Path("."),  # not used for resolution, just for typing
        )
        console.print(f"  [green]✓[/green] {len(scan.endpoint_bundles)} endpoint bundle(s)")
        for b in scan.endpoint_bundles:
            console.print(f"    • {b.endpoint_family}: {len(b.evidence)} evidence files, {len(b.methods_paths)} routes")

    # 2.3 Integration discovery
    if integration_mode == "auto" and cfg.get("include_integration_pages", True):
        console.print(f"  [bold]Discovering integrations...[/bold]")
        scan.integration_identities = discover_integrations(
            scan.parsed_files,
            scan.file_contents,
            scan.config_files,
            Path("."),
            llm=llm,
        )
        if scan.integration_identities:
            console.print(f"  [green]✓[/green] {len(scan.integration_identities)} integration(s) identified:")
            for i in scan.integration_identities:
                marker = "📄" if i.is_substantial else "📎"
                console.print(f"    {marker} {i.display_name} ({len(i.files)} files)")

    # 2.4 Artifact discovery
    console.print(f"  [bold]Scanning for setup/deploy/test artifacts...[/bold]")
    scan.artifact_scan = discover_artifacts(
        Path("."), scan.file_tree, scan.parsed_files, scan.file_contents,
    )
    a = scan.artifact_scan
    db_info = ""
    if a.database_scan and a.database_scan.model_files:
        db = a.database_scan
        db_info = f", {len(db.model_files)} model files ({db.total_models} models, ORM: {db.orm_framework or '?'})"
    console.print(
        f"  [green]✓[/green] {len(a.setup_artifacts)} setup, {len(a.deploy_artifacts)} deploy, "
        f"{len(a.ci_artifacts)} CI, {len(a.test_artifacts)} test, {len(a.ops_artifacts)} ops{db_info}"
    )

    return scan


# ─────────────────────────────────────────────────────────────────────────────
# Multi-Step Planner (3 LLM calls)
# ─────────────────────────────────────────────────────────────────────────────

# ── Step 1: Classify ─────────────────────────────────────────────────────────

CLASSIFY_SYSTEM = """\
You are a senior software architect analyzing a repository. Classify every file \
and artifact into categories. Respond with valid JSON only — no markdown, no \
explanation.
"""

CLASSIFY_PROMPT = """\
Analyze this repository and classify all files/artifacts.

## Repository Overview
- **Languages**: {languages}
- **Frameworks**: {frameworks}
- **Total source files**: {total_files}
- **API endpoints found**: {endpoint_count}
- **Entry points**: {entry_points}
- **Config files**: {config_files}

## Directory Structure
{file_tree}

## File Summaries
{file_summaries}

## API Endpoints
{endpoints}

---

Classify each source file into ONE primary category and optionally tag secondary roles.

Return JSON:
{{
  "source_files": {{
    "path/to/file.py": {{
      "primary": "handler|service|model|validator|serializer|middleware|util|config|route|task|test|migration|constant|type_def|auth|other",
      "secondary": ["integration_client", "webhook_handler", "queue_task", ...],
      "domain_hint": "orders|auth|payments|users|...",
      "line_count": 500
    }}
  }},
  "setup_artifacts": ["Dockerfile", "docker-compose.yml", ...],
  "test_artifacts": ["tests/...", ...],
  "deploy_artifacts": [".github/workflows/...", "Procfile", ...],
  "integration_signals": [
    {{
      "name": "short identifier like vinculum or juspay",
      "evidence": ["import VinculumClient from...", "VINCULUM_API_URL in .env", ...],
      "files": ["path/to/vinculum_client.py", "path/to/sync_task.py"]
    }}
  ],
  "cross_cutting": [
    {{
      "concern": "authentication|logging|error_handling|caching|database|rate_limiting|...",
      "files": ["path/to/middleware/auth.py", ...]
    }}
  ],
  "giant_files": ["path/to/huge_controller.py"]
}}

Rules:
- Every source file in {file_summaries} MUST appear in source_files.
- giant_files = any source file with {giant_file_threshold}+ lines.
- integration_signals: look for HTTP clients, SDK imports, env vars with API/URL/KEY \
  suffixes, webhook handlers, named wrappers, queue tasks that sync with external systems.
- cross_cutting: identify shared concerns that span multiple features — auth middleware, \
  error handlers, logging setup, database connection, caching layer, etc.
- domain_hint: your best guess at which business domain this file belongs to (orders, \
  users, products, payments, inventory, shipping, etc.). Use "shared" for utilities.
"""


# ── Step 2: Propose Buckets ──────────────────────────────────────────────────

PROPOSE_SYSTEM = """\
You are a senior documentation architect. Given a classified repository, propose \
documentation buckets. Respond with valid JSON only — no markdown, no explanation.

Bucket types:
- system: architecture, setup, testing, deployment/ops, auth/middleware, \
  observability, shared cross-cutting concerns
- database: dedicated database/schema documentation — ER diagrams, table definitions, \
  relationships, migrations. Use this when models/ORM are detected.
- feature: business workflows (checkout, cancel/refund, order status, etc.)
- endpoint: endpoint FAMILY documentation (all /orders/* endpoints grouped together)
- integration: external systems (payment providers, warehouses, delivery partners, etc.)

Rules:
- BE COMPREHENSIVE: create as many buckets as the codebase warrants. Every important \
  area deserves its own bucket. Do NOT artificially compress or merge areas.
- A feature bucket groups files by BUSINESS WORKFLOW, not by file path.
- An endpoint bucket covers an endpoint FAMILY (all /orders/* endpoints, not one per route).
- A system bucket covers cross-cutting concerns that span many features.
- A database bucket covers the data model, schema, ER diagrams, and migrations.
- An integration bucket covers a third-party system that appears in multiple files/flows.
- If an integration is trivial (used in one place, no setup complexity), embed it in the \
  relevant feature bucket instead of creating a standalone integration bucket.
- Every bucket MUST have required_sections and required_diagrams.
"""

PROPOSE_PROMPT = """\
Based on this repository classification, propose documentation buckets.

## Classification Summary
{classification_summary}

## API Endpoints ({endpoint_count} total)
{endpoints}

## Integration Signals
{integration_signals}

## Cross-Cutting Concerns
{cross_cutting}

## Giant Files (need decomposition)
{giant_files}

## Database / Schema Info
{database_info}

## Constraints
{max_pages_instruction}
- Must include at minimum: 1 system bucket for architecture/overview, 1 system bucket \
  for setup (if setup artifacts exist)
- If database models are detected, include a dedicated system bucket (or bucket_type "database") \
  for "Database & Schema" with required_sections including "er_diagram", "table_definitions", \
  "relationships", "migrations", and required_diagrams including "er_diagram"
- Feature buckets should represent business workflows, NOT file directories
- Endpoint buckets should group by resource family, NOT one-per-route
- Create as many buckets as needed for thorough coverage — prefer depth and completeness \
  over brevity. Every important area should have its own bucket.
- Individual per-endpoint reference pages will be created in a follow-up step — do NOT \
  create endpoint_ref buckets here. Focus on system, feature, endpoint (family), \
  integration, and database buckets only.

Return JSON:
{{
  "buckets": [
    {{
      "bucket_type": "system|feature|endpoint|integration|database",
      "title": "Page Title",
      "slug": "page-slug",
      "section": "Nav Section Name",
      "description": "What this page covers",
      "rationale": "Why this bucket exists and what it groups",
      "candidate_files": ["path/to/file.py", ...],
      "candidate_domains": ["orders", "payments"],
      "depends_on": ["other-bucket-slug"],
      "required_sections": ["overview", "main_workflows", "state_transitions", ...],
      "required_diagrams": ["architecture_flow", "sequence_diagram", "er_diagram", ...],
      "coverage_targets": ["OrderController checkout flow", "Juspay payment auth", ...]
    }}
  ],
  "nav_structure": {{
    "Overview": ["architecture"],
    "Getting Started": ["setup"],
    "Database": ["database-schema"],
    "Features": ["orders-checkout", "orders-management"],
    "API Reference": ["orders-api"],
    "API Endpoints": ["get-orders", "post-orders", "get-orders-id", "post-payments-initiate"],
    "Integrations": ["juspay-integration", "vinculum-integration"],
    "Operations": ["deployment", "testing"]
  }}
}}
"""


# ── Step 3: Assign ───────────────────────────────────────────────────────────

ASSIGN_SYSTEM = """\
You are a documentation planner finalizing file assignments. Given proposed \
documentation buckets and a full file inventory, assign every source file to at \
least one bucket. Respond with valid JSON only.

Rules:
- EVERY source file must be assigned to at least one bucket or explicitly skipped.
- A file CAN belong to multiple buckets if it serves multiple purposes.
- Only skip: pure test files, auto-generated files, type-only files with no logic.
- For giant files, assign to the bucket that covers its PRIMARY feature cluster. \
  Giant-file decomposition happens later in the pipeline.
- artifact_refs: config/env/deploy/test files relevant to this bucket.
- owned_symbols: specific classes/functions from shared files (for focused docs).
- For endpoint_ref buckets (individual endpoint pages), assign the handler file and \
  the specific handler function as owned_symbols.
- For database buckets, assign model definition files, migration files, and schema files.
"""

ASSIGN_PROMPT = """\
Finalize file assignments for these documentation buckets.

## Proposed Buckets
{proposed_buckets}

## All Source Files (must all be assigned or skipped)
{all_files}

## API Endpoints
{endpoints}

## Giant Files (assign to most relevant bucket, decomposition happens later)
{giant_files}

## Setup/Config Artifacts
{setup_artifacts}

---

Return JSON:
{{
  "buckets": [
    {{
      "slug": "bucket-slug",
      "owned_files": ["path/to/file.py", ...],
      "owned_symbols": ["ClassName.method_name", "function_name", ...],
      "artifact_refs": ["Dockerfile", ".env.example", ...],
      "priority": 0
    }}
  ],
  "skipped_files": ["test/...", "types/index.d.ts", ...],
  "file_to_buckets": {{
    "path/to/file.py": ["bucket-slug-1", "bucket-slug-2"]
  }}
}}

Important:
- Every file in the source file list MUST appear either in a bucket's owned_files \
  or in skipped_files.
- owned_symbols is optional but encouraged for large shared files — it tells the \
  generator which parts of a file are relevant to this specific bucket.
- priority: 0 = generate first (overview/architecture), higher = later.
"""


def plan_docs(scan: RepoScan, cfg: dict[str, Any], llm: LLMClient) -> DocPlan:
    """Run the multi-step planner.

    Phase 2 scans (giant-file clustering, endpoint bundles, integration discovery)
    run first to enrich the scan, then:
    Step 1: CLASSIFY — categorize every file/artifact
    Step 2: PROPOSE — create bucket candidates (no cap, LLM decides freely)
    Step 3: ASSIGN — map files to buckets, produce final plan
    Step 4: AUTO-GEN endpoint_ref buckets from scan data (one per endpoint)
    """
    from rich.live import Live
    from rich.text import Text

    # ── Phase 2 Scans (enrich before planning) ───────────────────────────
    console.print(Panel("[bold]Running Phase 2 scan upgrades[/bold]", border_style="green"))
    scan = run_phase2_scans(scan, cfg, llm)

    max_pages = cfg.get("max_pages", 0)
    giant_file_threshold = cfg.get("giant_file_lines", 2000)

    # Build shared context strings
    file_tree_str = _format_file_tree_compressed(scan.file_tree, scan.file_summaries)
    file_summaries_str = _format_summaries_compressed(scan.file_summaries)
    endpoints_str = _format_endpoints(scan.api_endpoints)
    lang_str = ", ".join(f"{lang} ({count})" for lang, count in sorted(scan.languages.items(), key=lambda x: -x[1]))
    fw_str = ", ".join(scan.frameworks_detected) or "none detected"

    # ── Step 1: Classify ─────────────────────────────────────────────────
    console.print(Panel("[bold]Planner Step 1/3: Classifying repository artifacts[/bold]", border_style="cyan"))

    classify_prompt = CLASSIFY_PROMPT.format(
        languages=lang_str,
        frameworks=fw_str,
        total_files=scan.total_files,
        endpoint_count=len(scan.api_endpoints),
        entry_points=", ".join(scan.entry_points[:10]) or "none",
        config_files=", ".join(scan.config_files[:15]) or "none",
        file_tree=file_tree_str[:15000],
        file_summaries=file_summaries_str[:20000],
        endpoints=endpoints_str[:5000],
        giant_file_threshold=giant_file_threshold,
    )

    classification = _llm_step(llm, CLASSIFY_SYSTEM, classify_prompt, "classify")
    if not classification:
        console.print("[yellow]⚠ Classification failed — falling back to auto-plan[/yellow]")
        return _fallback_plan(scan, cfg)

    _print_classification_summary(classification)

    # ── Step 2: Propose Buckets ──────────────────────────────────────────
    console.print(Panel("[bold]Planner Step 2/3: Proposing documentation buckets[/bold]", border_style="cyan"))

    # Build classification summary for the proposal step
    classification_summary = _build_classification_summary(classification)

    # Enrich with Phase 2 results if available
    if scan.integration_identities:
        integration_signals = "## Discovered Integration Identities (Phase 2)\n"
        for ident in scan.integration_identities:
            substantial_tag = "[SUBSTANTIAL — create standalone page]" if ident.is_substantial else "[EMBEDDED — keep in feature pages]"
            integration_signals += f"- **{ident.display_name}** ({ident.name}) {substantial_tag}\n"
            integration_signals += f"  Files: {', '.join(ident.files[:5])}\n"
            integration_signals += f"  Evidence: {', '.join(ident.evidence[:3])}\n"
    else:
        integration_signals = json.dumps(classification.get("integration_signals", []), indent=2)

    cross_cutting = json.dumps(classification.get("cross_cutting", []), indent=2)

    # Enrich giant files with cluster info from Phase 2
    giant_files_list = classification.get("giant_files", [])
    giant_parts = []
    for f in giant_files_list:
        lc = scan.file_line_counts.get(f, '?')
        cluster_info = ""
        if f in scan.giant_file_clusters:
            analysis = scan.giant_file_clusters[f]
            cluster_names = [c.cluster_name for c in analysis.clusters]
            cluster_info = f" → clusters: {', '.join(cluster_names)}"
        giant_parts.append(f"- {f} ({lc} lines){cluster_info}")
    giant_files_str = "\n".join(giant_parts) or "(none)"

    # Build database info from artifact_scan
    database_info = "(none detected)"
    if scan.artifact_scan and hasattr(scan.artifact_scan, "database_scan") and scan.artifact_scan.database_scan:
        db_scan = scan.artifact_scan.database_scan
        db_parts = [f"ORM: {db_scan.orm_framework or 'unknown'}", f"Total models: {db_scan.total_models}"]
        for mf in db_scan.model_files[:20]:
            if not mf.is_migration:
                models_str = ", ".join(mf.model_names[:10]) if mf.model_names else "?"
                db_parts.append(f"  - {mf.file_path}: [{models_str}]")
        if db_scan.migration_files:
            db_parts.append(f"  Migrations: {len(db_scan.migration_files)} files")
        if db_scan.schema_files:
            db_parts.append(f"  Schema files: {', '.join(db_scan.schema_files)}")
        database_info = "\n".join(db_parts)

    # Build max_pages instruction: 0 = no cap
    if max_pages and max_pages > 0:
        max_pages_instruction = f"- Maximum total buckets: {max_pages}"
    else:
        max_pages_instruction = (
            "- No hard limit on bucket count. Create as many buckets as needed for "
            "thorough, deep documentation. Quality and completeness matter most."
        )

    propose_prompt = PROPOSE_PROMPT.format(
        classification_summary=classification_summary,
        endpoint_count=len(scan.api_endpoints),
        endpoints=endpoints_str[:15000],
        integration_signals=integration_signals,
        cross_cutting=cross_cutting,
        giant_files=giant_files_str,
        database_info=database_info,
        max_pages_instruction=max_pages_instruction,
    )

    proposal = _llm_step(llm, PROPOSE_SYSTEM, propose_prompt, "propose")
    if not proposal:
        console.print("[yellow]⚠ Bucket proposal failed — falling back to auto-plan[/yellow]")
        return _fallback_plan(scan, cfg)

    _print_proposal_summary(proposal)

    # ── Step 3: Assign Files ─────────────────────────────────────────────
    console.print(Panel("[bold]Planner Step 3/3: Assigning files to buckets[/bold]", border_style="cyan"))

    proposed_buckets_str = json.dumps(proposal.get("buckets", []), indent=2)
    all_files_str = "\n".join(f"- {f}" for f in sorted(scan.file_summaries.keys()))
    setup_artifacts_str = "\n".join(f"- {f}" for f in scan.config_files) or "(none)"

    assign_prompt = ASSIGN_PROMPT.format(
        proposed_buckets=proposed_buckets_str[:15000],
        all_files=all_files_str[:12000],
        endpoints=endpoints_str[:3000],
        giant_files=giant_files_str,
        setup_artifacts=setup_artifacts_str,
    )

    assignment = _llm_step(llm, ASSIGN_SYSTEM, assign_prompt, "assign")
    if not assignment:
        console.print("[yellow]⚠ Assignment failed — falling back to auto-plan[/yellow]")
        return _fallback_plan(scan, cfg)

    # ── Merge proposal + assignment into final plan ──────────────────────
    plan = _merge_plan(proposal, assignment, classification, scan)

    # ── Step 4: Auto-generate per-endpoint reference pages from scan data ─
    plan = _auto_generate_endpoint_refs(plan, scan)

    # Validate coverage
    console.print("[dim]Validating file coverage...[/dim]")
    plan = _validate_coverage(plan, scan)
    if plan.orphaned_files:
        console.print(f"[yellow]⚠ {len(plan.orphaned_files)} file(s) were unassigned → auto-assigned[/yellow]")

    _print_plan_summary(plan)
    return plan


def _llm_step(llm: LLMClient, system: str, prompt: str, step_name: str) -> dict | None:
    """Execute a single LLM planning step with error handling."""
    from rich.live import Live
    from rich.text import Text

    response = None
    with Live(
        Text(f"⠋ Running planner step: {step_name}... (may take 15-30s)", style="bold cyan"),
        console=console,
        refresh_per_second=10,
        transient=True,
    ):
        try:
            response = llm.complete(system, prompt)
        except Exception as e:
            console.print(f"[red]✗ LLM call failed for {step_name}: {e}[/red]")
            return None

    if not response:
        return None

    try:
        return _parse_json_response(response)
    except Exception as e:
        console.print(f"[red]✗ Could not parse {step_name} response: {e}[/red]")
        # Try to salvage — sometimes the LLM wraps JSON in markdown
        try:
            # Strip markdown fences and retry
            cleaned = response.strip()
            if cleaned.startswith("```"):
                lines = cleaned.splitlines()
                lines = [l for l in lines if not l.strip().startswith("```")]
                cleaned = "\n".join(lines)
            return json.loads(cleaned)
        except Exception:
            return None


def _parse_json_response(response: str) -> dict:
    """Extract JSON from LLM response, handling markdown fences."""
    text = response.strip()
    if text.startswith("```"):
        lines = text.splitlines()
        lines = [l for l in lines if not l.strip().startswith("```")]
        text = "\n".join(lines)
    return json.loads(text)


# ─────────────────────────────────────────────────────────────────────────────
# Merge proposal + assignment into final DocPlan
# ─────────────────────────────────────────────────────────────────────────────

def _merge_plan(
    proposal: dict,
    assignment: dict,
    classification: dict,
    scan: RepoScan,
) -> DocPlan:
    """Combine the proposal (bucket definitions) with the assignment (file mapping)."""
    # Index proposed buckets by slug
    proposed_by_slug: dict[str, dict] = {}
    for b in proposal.get("buckets", []):
        proposed_by_slug[b["slug"]] = b

    # Index assignments by slug
    assigned_by_slug: dict[str, dict] = {}
    for a in assignment.get("buckets", []):
        assigned_by_slug[a["slug"]] = a

    buckets: list[DocBucket] = []
    for slug, prop in proposed_by_slug.items():
        assign = assigned_by_slug.get(slug, {})

        bucket = DocBucket(
            bucket_type=prop.get("bucket_type", "feature"),
            title=prop.get("title", slug),
            slug=slug,
            section=prop.get("section", ""),
            description=prop.get("description", ""),
            depends_on=prop.get("depends_on", []),
            owned_files=assign.get("owned_files", prop.get("candidate_files", [])),
            owned_symbols=assign.get("owned_symbols", []),
            artifact_refs=assign.get("artifact_refs", []),
            required_sections=prop.get("required_sections", _default_sections(prop.get("bucket_type", "feature"))),
            required_diagrams=prop.get("required_diagrams", []),
            coverage_targets=prop.get("coverage_targets", []),
            priority=assign.get("priority", 0),
        )
        buckets.append(bucket)

    # Sort by priority
    buckets.sort(key=lambda b: b.priority)

    nav_structure = proposal.get("nav_structure", {})
    skipped_files = assignment.get("skipped_files", [])

    return DocPlan(
        buckets=buckets,
        nav_structure=nav_structure,
        skipped_files=skipped_files,
        classification=classification,
        integration_candidates=classification.get("integration_signals", []),
    )


def _auto_generate_endpoint_refs(plan: DocPlan, scan: RepoScan) -> DocPlan:
    """Auto-generate individual endpoint_ref buckets from scan API endpoints.

    This creates one page per API endpoint (e.g. GET /api/v1/orders) and nests
    each under its parent endpoint-family bucket. The LLM planner only creates
    family buckets (endpoint type) — this fills in the per-endpoint detail pages.
    """
    import re as _re

    if not scan.api_endpoints:
        return plan

    # Map endpoints to their family bucket by matching resource group
    family_buckets = [b for b in plan.buckets if b.bucket_type == "endpoint"]

    # Build resource → family bucket slug mapping
    def _resource_from_path(path: str) -> str:
        clean = _re.sub(r"^/(?:api/)?(?:v\d+/)?", "", path)
        parts_list = [p for p in clean.split("/") if p and not p.startswith(":") and not p.startswith("{")]
        return parts_list[0] if parts_list else "general"

    resource_to_family: dict[str, str] = {}
    for fb in family_buckets:
        # Derive resource from slug (e.g. "orders-api" → "orders")
        resource = fb.slug.replace("-api", "").replace("-", "_")
        resource_to_family[resource] = fb.slug
        # Also map without underscores
        resource_to_family[resource.replace("_", "-")] = fb.slug

    ref_buckets: list[DocBucket] = []
    existing_slugs = {b.slug for b in plan.buckets}

    for ep in scan.api_endpoints:
        method = ep.get("method", "GET").upper()
        path = ep.get("path", "/unknown")
        handler = ep.get("handler", "")
        ep_file = ep.get("file", "")

        # Build slug
        path_slug = _re.sub(r"[/:{}]+", "-", path).strip("-").lower()
        ref_slug = f"{method.lower()}-{path_slug}"

        # Avoid duplicates
        if ref_slug in existing_slugs:
            continue
        existing_slugs.add(ref_slug)

        # Find parent family bucket
        resource = _resource_from_path(path)
        parent_slug = resource_to_family.get(resource, resource_to_family.get(resource.replace("_", "-"), ""))

        ref_buckets.append(DocBucket(
            bucket_type="endpoint_ref",
            title=f"{method} {path}",
            slug=ref_slug,
            section="API Endpoints",
            description=f"API reference for {method} {path} — handler: {handler}",
            owned_files=[ep_file] if ep_file else [],
            owned_symbols=[handler] if handler else [],
            required_sections=_default_sections("endpoint_ref"),
            priority=25,
            depends_on=[parent_slug] if parent_slug else [],
        ))

    if ref_buckets:
        plan.buckets.extend(ref_buckets)

        # Group endpoint_refs by family in nav — nested under parent family title
        family_slug_to_title: dict[str, str] = {
            b.slug: b.title for b in plan.buckets if b.bucket_type == "endpoint"
        }
        family_refs: dict[str, list[str]] = defaultdict(list)
        ungrouped: list[str] = []
        for b in ref_buckets:
            parent = b.depends_on[0] if b.depends_on else ""
            if parent and parent in family_slug_to_title:
                family_refs[parent].append(b.slug)
            else:
                ungrouped.append(b.slug)

        # Build nested nav sections: "API Endpoints > Orders API" etc.
        for family_slug, ref_slugs in sorted(family_refs.items()):
            family_title = family_slug_to_title.get(family_slug, family_slug)
            section_key = f"API Endpoints > {family_title}"
            # Include the family overview page first, then individual endpoints
            plan.nav_structure[section_key] = [family_slug] + ref_slugs
            # Remove family slug from its original section so it's not duplicated
            for section_name, slugs in list(plan.nav_structure.items()):
                if section_name != section_key and family_slug in slugs:
                    slugs.remove(family_slug)

        if ungrouped:
            plan.nav_structure["API Endpoints > Other"] = ungrouped

        console.print(f"[green]✓ Auto-generated {len(ref_buckets)} individual endpoint reference pages[/green]")

    return plan


def _default_sections(bucket_type: str) -> list[str]:
    """Default required sections per bucket type."""
    if bucket_type == "system":
        return ["overview", "architecture", "key_components", "configuration", "diagrams"]
    elif bucket_type == "feature":
        return ["overview", "main_workflows", "participating_endpoints", "core_helpers",
                "state_transitions", "integrations_involved", "config_dependencies",
                "edge_cases", "diagrams"]
    elif bucket_type == "endpoint":
        return ["route_overview", "auth_validation", "execution_flow", "downstream_calls",
                "integrations_touched", "state_changes", "async_side_effects",
                "response_errors", "diagrams"]
    elif bucket_type == "integration":
        return ["what_it_does", "where_it_enters", "participating_features",
                "request_response_flow", "auth_configuration", "retry_failure_handling",
                "operational_gotchas", "diagrams"]
    elif bucket_type == "endpoint_ref":
        return ["endpoint_summary", "handler", "parameters", "request_body",
                "response_format", "error_responses", "auth", "sequence_diagram"]
    elif bucket_type == "database":
        return ["overview", "er_diagram", "table_definitions", "relationships",
                "migrations", "query_patterns", "configuration"]
    return ["overview", "details", "diagrams"]


# ─────────────────────────────────────────────────────────────────────────────
# Coverage validation
# ─────────────────────────────────────────────────────────────────────────────

def _validate_coverage(plan: DocPlan, scan: RepoScan) -> DocPlan:
    """Ensure all important source files are assigned to at least one bucket."""
    all_assigned: set[str] = set()
    for bucket in plan.buckets:
        all_assigned.update(bucket.owned_files)
    skipped = set(plan.skipped_files)

    all_source = set(scan.file_summaries.keys())
    orphaned = all_source - all_assigned - skipped

    if orphaned:
        orphan_groups: dict[str, list[str]] = defaultdict(list)
        for f in orphaned:
            parts = f.split("/")
            group = parts[0] if len(parts) > 1 else "root"
            orphan_groups[group].append(f)

        for group_name, files in orphan_groups.items():
            # Try to find an existing bucket that covers this directory
            matched = False
            for bucket in plan.buckets:
                if any(f.startswith(group_name + "/") for f in bucket.owned_files):
                    bucket.owned_files.extend(files)
                    matched = True
                    break

            if not matched:
                # Create a catch-all feature bucket
                plan.buckets.append(DocBucket(
                    bucket_type="feature",
                    title=f"{group_name.replace('_', ' ').replace('-', ' ').title()} Module",
                    slug=f"{group_name.lower().replace(' ', '-').replace('_', '-')}-module",
                    section="Modules",
                    description=f"Documentation for the {group_name} module",
                    owned_files=files,
                    required_sections=_default_sections("feature"),
                    priority=50,
                ))
                if "Modules" not in plan.nav_structure:
                    plan.nav_structure["Modules"] = []
                plan.nav_structure["Modules"].append(plan.buckets[-1].slug)

        plan.orphaned_files = sorted(orphaned)

    return plan


# ─────────────────────────────────────────────────────────────────────────────
# Fallback plan (if LLM fails at any step)
# ─────────────────────────────────────────────────────────────────────────────

def _fallback_plan(scan: RepoScan, cfg: dict[str, Any]) -> DocPlan:
    """Generate a reasonable bucket-based plan without LLM, using repo structure."""
    import re

    buckets: list[DocBucket] = []
    nav: dict[str, list[str]] = defaultdict(list)
    assigned_files: set[str] = set()

    # ── System bucket: Architecture/Overview ─────────────────────────────
    overview_files = scan.entry_points[:5] + scan.config_files[:3]
    buckets.append(DocBucket(
        bucket_type="system",
        title="Architecture & Overview",
        slug="architecture",
        section="Overview",
        description="Project overview, architecture, and high-level design",
        owned_files=overview_files,
        required_sections=_default_sections("system"),
        priority=0,
    ))
    nav["Overview"].append("architecture")
    assigned_files.update(overview_files)

    # ── System bucket: Setup ─────────────────────────────────────────────
    if scan.config_files:
        buckets.append(DocBucket(
            bucket_type="system",
            title="Setup & Configuration",
            slug="setup",
            section="Getting Started",
            description="Installation, environment variables, and configuration",
            owned_files=[],
            artifact_refs=scan.config_files[:10],
            required_sections=["overview", "prerequisites", "installation", "configuration",
                               "environment_variables", "verification"],
            priority=1,
        ))
        nav["Getting Started"].append("setup")

    # ── Categorize files ─────────────────────────────────────────────────
    ROLE_DIRS = {
        "middleware": ["middleware", "middlewares"],
        "models": ["model", "models", "schemas", "entities"],
        "routes": ["route", "routes", "router", "routers"],
        "controllers": ["controller", "controllers", "handlers"],
        "services": ["service", "services"],
        "utils": ["util", "utils", "helpers", "lib", "common"],
        "config": ["config", "configs", "settings"],
    }

    dir_to_role: dict[str, str] = {}
    for role, dir_names in ROLE_DIRS.items():
        for d in dir_names:
            dir_to_role[d] = role

    role_buckets_map: dict[str, list[str]] = defaultdict(list)
    domain_buckets_map: dict[str, list[str]] = defaultdict(list)

    for rel_path in scan.file_summaries:
        parts = rel_path.split("/")
        if any(p in ("tests", "test", "__tests__", "spec") for p in parts):
            continue

        matched_role = None
        for part in parts:
            if part.lower() in dir_to_role:
                matched_role = dir_to_role[part.lower()]
                break

        if matched_role:
            role_buckets_map[matched_role].append(rel_path)
        else:
            if len(parts) >= 3 and parts[0] in ("src", "api", "app", "pkg", "internal"):
                group = parts[1]
            elif len(parts) >= 2:
                group = parts[0]
            else:
                group = "root"
            domain_buckets_map[group].append(rel_path)

    # ── Database bucket: Schema & Models ────────────────────────────────
    model_files = role_buckets_map.get("models", [])
    # Also grab model files from database scan if available
    db_model_files: list[str] = list(model_files)
    if scan.artifact_scan and hasattr(scan.artifact_scan, "database_scan") and scan.artifact_scan.database_scan:
        db_scan = scan.artifact_scan.database_scan
        for mf in db_scan.model_files:
            if mf.file_path not in db_model_files:
                db_model_files.append(mf.file_path)
        db_model_files.extend(f for f in db_scan.schema_files if f not in db_model_files)
    if db_model_files:
        buckets.append(DocBucket(
            bucket_type="database",
            title="Database & Schema",
            slug="database-schema",
            section="Database",
            description="Database schemas, models, ER diagrams, relationships, and migrations",
            owned_files=db_model_files,
            required_sections=_default_sections("database"),
            required_diagrams=["er_diagram"],
            priority=3,
        ))
        nav["Database"].append("database-schema")
        assigned_files.update(db_model_files)

    # ── System bucket: Middleware & Auth ──────────────────────────────────
    mw_files = role_buckets_map.get("middleware", [])
    if mw_files:
        buckets.append(DocBucket(
            bucket_type="system",
            title="Middleware & Authentication",
            slug="middleware-auth",
            section="Architecture",
            description="Authentication, authorization, rate limiting, and middleware pipeline",
            owned_files=mw_files,
            required_sections=_default_sections("system"),
            priority=4,
        ))
        nav["Architecture"].append("middleware-auth")
        assigned_files.update(mw_files)

    # ── Feature buckets from domain dirs ─────────────────────────────────
    for group_name, files in sorted(domain_buckets_map.items()):
        if group_name in (".", "root") and len(files) <= 2:
            buckets[0].owned_files.extend(files)
            assigned_files.update(files)
            continue

        slug = f"{group_name.lower().replace(' ', '-').replace('_', '-')}"
        buckets.append(DocBucket(
            bucket_type="feature",
            title=f"{group_name.replace('_', ' ').replace('-', ' ').title()}",
            slug=slug,
            section="Features",
            description=f"Documentation for {group_name} feature area",
            owned_files=files,
            required_sections=_default_sections("feature"),
            priority=10,
        ))
        nav["Features"].append(slug)
        assigned_files.update(files)

    # ── Remaining role-based files ───────────────────────────────────────
    for role in ["controllers", "services", "utils", "routes", "config"]:
        files = [f for f in role_buckets_map.get(role, []) if f not in assigned_files]
        if not files:
            continue
        # Try to merge into an existing feature bucket
        merged = False
        for bucket in buckets:
            if bucket.bucket_type == "feature":
                overlap = set(f.split("/")[0] for f in files) & set(f.split("/")[0] for f in bucket.owned_files)
                if overlap:
                    bucket.owned_files.extend(files)
                    assigned_files.update(files)
                    merged = True
                    break
        if not merged:
            buckets.append(DocBucket(
                bucket_type="feature",
                title=f"{role.replace('_', ' ').title()}",
                slug=f"{role}",
                section="Modules",
                description=f"{role.title()} layer documentation",
                owned_files=files,
                required_sections=_default_sections("feature"),
                priority=15,
            ))
            nav["Modules"].append(role)
            assigned_files.update(files)

    # ── Endpoint bucket ──────────────────────────────────────────────────
    if scan.api_endpoints:
        resource_groups: dict[str, list[dict]] = defaultdict(list)
        for ep in scan.api_endpoints:
            path = ep.get("path", "")
            clean = re.sub(r"^/(?:api/)?(?:v\d+/)?", "", path)
            parts_list = [p for p in clean.split("/") if p and not p.startswith(":") and not p.startswith("{")]
            resource = parts_list[0] if parts_list else "general"
            resource_groups[resource].append(ep)

        for resource, eps in sorted(resource_groups.items()):
            ep_files = sorted(set(ep["file"] for ep in eps))
            slug = f"{resource}-api"
            buckets.append(DocBucket(
                bucket_type="endpoint",
                title=f"{resource.replace('_', ' ').replace('-', ' ').title()} API",
                slug=slug,
                section="API Reference",
                description=f"API reference for {resource} endpoints ({len(eps)} endpoints)",
                owned_files=ep_files,
                required_sections=_default_sections("endpoint"),
                priority=20,
            ))
            nav["API Reference"].append(slug)
            assigned_files.update(ep_files)

            # Individual endpoint_ref pages for each endpoint in this family
            for ep in eps:
                method = ep.get("method", "GET").upper()
                path = ep.get("path", "/unknown")
                handler = ep.get("handler", "")
                ep_file = ep.get("file", "")
                # Build a slug from method + path
                path_slug = re.sub(r"[/:{}]+", "-", path).strip("-").lower()
                ref_slug = f"{method.lower()}-{path_slug}"
                ref_title = f"{method} {path}"
                buckets.append(DocBucket(
                    bucket_type="endpoint_ref",
                    title=ref_title,
                    slug=ref_slug,
                    section="API Endpoints",
                    description=f"API reference for {method} {path} — handler: {handler}",
                    owned_files=[ep_file] if ep_file else [],
                    owned_symbols=[handler] if handler else [],
                    required_sections=_default_sections("endpoint_ref"),
                    priority=25,
                    depends_on=[slug],
                ))
                nav["API Endpoints"].append(ref_slug)

    # ── Skipped files ────────────────────────────────────────────────────
    all_source = set(scan.file_summaries.keys())
    test_files = sorted(f for f in all_source if any(
        p in f.split("/") for p in ("tests", "test", "__tests__", "spec")
    ))

    return DocPlan(
        buckets=buckets,
        nav_structure=dict(nav),
        skipped_files=test_files,
    )


# ─────────────────────────────────────────────────────────────────────────────
# Formatting helpers
# ─────────────────────────────────────────────────────────────────────────────

def _format_file_tree_compressed(tree: dict[str, list[str]], summaries: dict[str, str]) -> str:
    """Compress file tree to directory-level summaries so 300+ files fit."""
    lines = []
    for dir_path in sorted(tree.keys()):
        files = tree[dir_path]
        if not files:
            continue
        ext_counts: dict[str, int] = defaultdict(int)
        for f in files:
            ext = f.rsplit(".", 1)[-1] if "." in f else "other"
            ext_counts[ext] += 1
        ext_summary = ", ".join(f"{count} .{ext}" for ext, count in sorted(ext_counts.items(), key=lambda x: -x[1]))
        shown = sorted(files)[:5]
        rest = len(files) - len(shown)
        file_list = ", ".join(shown) + (f", +{rest} more" if rest > 0 else "")
        lines.append(f"\n{dir_path}/ ({len(files)} files: {ext_summary})")
        lines.append(f"  Files: {file_list}")
        all_symbols: list[str] = []
        for rel_path, summary in summaries.items():
            file_dir = "/".join(rel_path.split("/")[:-1]) if "/" in rel_path else "."
            if file_dir == dir_path and "symbols=[" in summary:
                try:
                    sym_part = summary.split("symbols=[")[1].split("]")[0]
                    names = [s.split(":")[-1].strip() for s in sym_part.split(",") if ":" in s]
                    all_symbols.extend(names[:5])
                except Exception:
                    pass
        if all_symbols:
            lines.append(f"  Key symbols: {', '.join(all_symbols[:12])}")
    return "\n".join(lines)


def _format_summaries_compressed(summaries: dict[str, str]) -> str:
    """Compressed per-file summaries."""
    lines: list[str] = []
    for path in sorted(summaries.keys()):
        summary = summaries[path]
        line_count = ""
        if "lines=" in summary:
            try:
                line_count = summary.split("lines=")[-1].split("|")[0].strip()
                line_count = f" ({line_count}L)"
            except Exception:
                pass
        symbols = ""
        if "symbols=[" in summary:
            try:
                sym_part = summary.split("symbols=[")[1].split("]")[0]
                names = [s.split(":")[-1].strip() for s in sym_part.split(",") if ":" in s]
                if names:
                    symbols = f" → {', '.join(names[:8])}"
                    if len(names) > 8:
                        symbols += f" +{len(names) - 8}"
            except Exception:
                pass
        lines.append(f"- {path}{line_count}{symbols}")
    return "\n".join(lines)


def _format_endpoints(endpoints: list[dict]) -> str:
    if not endpoints:
        return "(none)"
    lines = []
    for ep in endpoints[:50]:
        lines.append(f"- {ep['method']} {ep['path']} → {ep.get('handler', '?')} ({ep.get('file', '')}:{ep.get('line', 0)})")
    if len(endpoints) > 50:
        lines.append(f"... +{len(endpoints) - 50} more endpoints")
    return "\n".join(lines)


def _build_classification_summary(classification: dict) -> str:
    """Build a human-readable summary of the classification for Step 2."""
    lines = []

    source_files = classification.get("source_files", {})
    # Count by primary role
    role_counts: dict[str, int] = defaultdict(int)
    domain_counts: dict[str, int] = defaultdict(int)
    for path, info in source_files.items():
        if isinstance(info, dict):
            role_counts[info.get("primary", "other")] += 1
            domain = info.get("domain_hint", "unknown")
            if domain:
                domain_counts[domain] += 1

    lines.append("### File Roles")
    for role, count in sorted(role_counts.items(), key=lambda x: -x[1]):
        lines.append(f"- {role}: {count} files")

    lines.append("\n### Business Domains")
    for domain, count in sorted(domain_counts.items(), key=lambda x: -x[1]):
        lines.append(f"- {domain}: {count} files")

    lines.append(f"\n### Setup artifacts: {len(classification.get('setup_artifacts', []))}")
    lines.append(f"### Test artifacts: {len(classification.get('test_artifacts', []))}")
    lines.append(f"### Deploy artifacts: {len(classification.get('deploy_artifacts', []))}")
    lines.append(f"### Integration signals: {len(classification.get('integration_signals', []))}")
    lines.append(f"### Cross-cutting concerns: {len(classification.get('cross_cutting', []))}")
    lines.append(f"### Giant files: {len(classification.get('giant_files', []))}")

    return "\n".join(lines)


# ─────────────────────────────────────────────────────────────────────────────
# Rich printing helpers
# ─────────────────────────────────────────────────────────────────────────────

def _print_classification_summary(classification: dict) -> None:
    """Print a rich summary of the classification step."""
    source_files = classification.get("source_files", {})
    integrations = classification.get("integration_signals", [])
    cross_cutting = classification.get("cross_cutting", [])
    giant_files = classification.get("giant_files", [])

    console.print(f"  [green]✓[/green] Classified {len(source_files)} source files")
    if integrations:
        names = [i.get("name", "?") for i in integrations]
        console.print(f"  [green]✓[/green] Found {len(integrations)} integration signal(s): {', '.join(names)}")
    if cross_cutting:
        concerns = [c.get("concern", "?") for c in cross_cutting]
        console.print(f"  [green]✓[/green] Found {len(cross_cutting)} cross-cutting concern(s): {', '.join(concerns)}")
    if giant_files:
        console.print(f"  [yellow]⚠[/yellow] {len(giant_files)} giant file(s) detected: {', '.join(giant_files[:5])}")


def _print_proposal_summary(proposal: dict) -> None:
    """Print a rich summary of the proposed buckets."""
    buckets = proposal.get("buckets", [])
    by_type: dict[str, int] = defaultdict(int)
    for b in buckets:
        by_type[b.get("bucket_type", "?")] += 1

    console.print(f"  [green]✓[/green] Proposed {len(buckets)} buckets:")
    for btype, count in sorted(by_type.items()):
        console.print(f"    • {btype}: {count}")


def _print_plan_summary(plan: DocPlan) -> None:
    """Print the final plan as a rich table."""
    table = Table(title="Documentation Plan (Bucket-Based)", show_header=True, header_style="bold")
    table.add_column("#", style="dim", width=3)
    table.add_column("Bucket", style="cyan")
    table.add_column("Type", style="green")
    table.add_column("Section")
    table.add_column("Files", justify="right")
    table.add_column("Sections", justify="right")
    table.add_column("Depends On", style="dim")

    for i, bucket in enumerate(plan.buckets, 1):
        deps = ", ".join(bucket.depends_on[:3])
        if len(bucket.depends_on) > 3:
            deps += f" +{len(bucket.depends_on) - 3}"
        table.add_row(
            str(i),
            bucket.title,
            bucket.bucket_type,
            bucket.section,
            str(len(bucket.owned_files)),
            str(len(bucket.required_sections)),
            deps or "—",
        )

    console.print(table)

    total_files = sum(len(b.owned_files) for b in plan.buckets)
    type_counts = defaultdict(int)
    for b in plan.buckets:
        type_counts[b.bucket_type] += 1
    type_str = ", ".join(f"{count} {btype}" for btype, count in sorted(type_counts.items()))

    console.print(
        f"\n[dim]{len(plan.buckets)} buckets ({type_str}) covering {total_files} source files | "
        f"{len(plan.skipped_files)} files skipped"
        f"{f' | {len(plan.orphaned_files)} orphaned → auto-assigned' if plan.orphaned_files else ''}[/dim]"
    )


def _matches_any(path: str, patterns: list[str]) -> bool:
    for pattern in patterns:
        if fnmatch.fnmatch(path, pattern) or fnmatch.fnmatch(os.path.basename(path), pattern) or pattern in path.split(os.sep):
            return True
    return False
