        // CodeWiki-managed file. Regenerated by `codewiki generate`.
        import type { Root } from 'fumadocs-core/page-tree';

        export const pageTree: Root = {
  "name": "codewiki",
  "children": [
    {
      "type": "page",
      "name": "System Architecture & Overview",
      "url": "/"
    },
    {
      "type": "folder",
      "name": "Overview",
      "children": [
        {
          "type": "page",
          "name": "System Architecture & Overview",
          "url": "/"
        },
        {
          "type": "page",
          "name": "Setup & Getting Started",
          "url": "/setup-getting-started"
        }
      ]
    },
    {
      "type": "folder",
      "name": "Core Features",
      "children": [
        {
          "type": "page",
          "name": "Chatbot Core Logic",
          "url": "/chatbot-core"
        },
        {
          "type": "page",
          "name": "User Management & Profiles",
          "url": "/user-management"
        },
        {
          "type": "page",
          "name": "Parser Engine & API Detection",
          "url": "/parser-engine"
        },
        {
          "type": "page",
          "name": "Site Builder & Fumadocs Integration",
          "url": "/site-builder"
        },
        {
          "type": "page",
          "name": "LLM Client & Providers",
          "url": "/llm-client"
        },
        {
          "type": "page",
          "name": "State Sync & Persistence",
          "url": "/state-sync"
        },
        {
          "type": "page",
          "name": "Chatbot Indexer",
          "url": "/chatbot-indexer"
        }
      ]
    },
    {
      "type": "folder",
      "name": "Data & Persistence",
      "children": [
        {
          "type": "page",
          "name": "Database Models & Persistence",
          "url": "/database-models"
        }
      ]
    },
    {
      "type": "folder",
      "name": "Integrations",
      "children": [
        {
          "type": "page",
          "name": "Anthropic Integration",
          "url": "/integration-anthropic"
        },
        {
          "type": "page",
          "name": "CodeWiki Chat Integration",
          "url": "/integration-codewiki-chat"
        },
        {
          "type": "page",
          "name": "CodeWiki Embed Integration",
          "url": "/integration-codewiki-embed"
        },
        {
          "type": "page",
          "name": "Vinculum Warehouse Management Integration",
          "url": "/integration-vinculum"
        },
        {
          "type": "page",
          "name": "Webhook Integrations",
          "url": "/integration-webhooks"
        }
      ]
    },
    {
      "type": "folder",
      "name": "Operations",
      "children": [
        {
          "type": "page",
          "name": "Testing & Quality Assurance",
          "url": "/testing-qa"
        },
        {
          "type": "page",
          "name": "Deployment & Operations",
          "url": "/deployment-operations"
        }
      ]
    },
    {
      "type": "folder",
      "name": "API Endpoints",
      "children": [
        {
          "type": "folder",
          "name": "Other",
          "children": [
            {
              "type": "page",
              "name": "GET /health",
              "url": "/get-health"
            },
            {
              "type": "page",
              "name": "POST /query",
              "url": "/post-query"
            },
            {
              "type": "page",
              "name": "ANY /things",
              "url": "/any-things"
            },
            {
              "type": "page",
              "name": "POST /health",
              "url": "/post-health"
            },
            {
              "type": "page",
              "name": "GET /reports/{slug}",
              "url": "/get-reports-slug"
            },
            {
              "type": "page",
              "name": "GET /api/users",
              "url": "/get-api-users"
            },
            {
              "type": "page",
              "name": "POST /api/users",
              "url": "/post-api-users"
            },
            {
              "type": "page",
              "name": "GET /api/users/{id}",
              "url": "/get-api-users-id"
            },
            {
              "type": "page",
              "name": "DELETE /api/users/{id}",
              "url": "/delete-api-users-id"
            },
            {
              "type": "page",
              "name": "GET /api/users/{id}/stats",
              "url": "/get-api-users-id-stats"
            },
            {
              "type": "page",
              "name": "GET /api/v1/users",
              "url": "/get-api-v1-users"
            },
            {
              "type": "page",
              "name": "POST /api/v1/users",
              "url": "/post-api-v1-users"
            },
            {
              "type": "page",
              "name": "GET /api/v1/admin/stats",
              "url": "/get-api-v1-admin-stats"
            }
          ]
        }
      ]
    }
  ]
};
