        // CodeWiki-managed file. Regenerated by `codewiki generate`.
        import type { Root } from 'fumadocs-core/page-tree';

        export const pageTree: Root = {
  "name": "codewiki",
  "children": [
    {
      "type": "page",
      "name": "System Architecture & Overview",
      "url": "/"
    },
    {
      "type": "folder",
      "name": "Overview",
      "children": [
        {
          "type": "page",
          "name": "System Architecture & Overview",
          "url": "/"
        },
        {
          "type": "page",
          "name": "Setup & Getting Started",
          "url": "/setup-getting-started"
        }
      ]
    },
    {
      "type": "folder",
      "name": "Core Features",
      "children": [
        {
          "type": "page",
          "name": "User Management",
          "url": "/user-management"
        }
      ]
    },
    {
      "type": "folder",
      "name": "API Families",
      "children": [
        {
          "type": "page",
          "name": "Things Resource API",
          "url": "/things-resource-api"
        },
        {
          "type": "page",
          "name": "Health & Monitoring Endpoints",
          "url": "/health-monitoring"
        }
      ]
    },
    {
      "type": "folder",
      "name": "Data & Models",
      "children": [
        {
          "type": "page",
          "name": "Database Models & Schema",
          "url": "/database-models"
        }
      ]
    },
    {
      "type": "folder",
      "name": "Integrations",
      "children": [
        {
          "type": "page",
          "name": "Anthropic Integration",
          "url": "/anthropic-integration"
        },
        {
          "type": "page",
          "name": "Vinculum Warehouse Management Integration",
          "url": "/vinculum-integration"
        },
        {
          "type": "page",
          "name": "Webhooks & Event Handling",
          "url": "/webhook-integration"
        }
      ]
    },
    {
      "type": "folder",
      "name": "Operations",
      "children": [
        {
          "type": "page",
          "name": "Testing & Quality Assurance",
          "url": "/testing-quality"
        },
        {
          "type": "page",
          "name": "Deployment & Operations",
          "url": "/deployment-operations"
        }
      ]
    },
    {
      "type": "folder",
      "name": "API Endpoints",
      "children": [
        {
          "type": "folder",
          "name": "Reports API",
          "children": [
            {
              "type": "page",
              "name": "Reports API",
              "url": "/reports-api"
            },
            {
              "type": "page",
              "name": "GET /reports/{slug}",
              "url": "/get-reports-slug"
            }
          ]
        },
        {
          "type": "folder",
          "name": "Other",
          "children": [
            {
              "type": "page",
              "name": "ANY /things",
              "url": "/any-things"
            },
            {
              "type": "page",
              "name": "GET /health",
              "url": "/get-health"
            },
            {
              "type": "page",
              "name": "POST /health",
              "url": "/post-health"
            },
            {
              "type": "page",
              "name": "GET /api/users",
              "url": "/get-api-users"
            },
            {
              "type": "page",
              "name": "POST /api/users",
              "url": "/post-api-users"
            },
            {
              "type": "page",
              "name": "GET /api/users/{id}",
              "url": "/get-api-users-id"
            },
            {
              "type": "page",
              "name": "DELETE /api/users/{id}",
              "url": "/delete-api-users-id"
            },
            {
              "type": "page",
              "name": "GET /api/users/{id}/stats",
              "url": "/get-api-users-id-stats"
            },
            {
              "type": "page",
              "name": "GET /api/v1/users",
              "url": "/get-api-v1-users"
            },
            {
              "type": "page",
              "name": "POST /api/v1/users",
              "url": "/post-api-v1-users"
            },
            {
              "type": "page",
              "name": "GET /api/v1/admin/stats",
              "url": "/get-api-v1-admin-stats"
            }
          ]
        }
      ]
    }
  ]
};
