        // CodeWiki-managed file. Regenerated by `codewiki generate`.
        import type { Root } from 'fumadocs-core/page-tree';

        export const pageTree: Root = {
  "name": "codewiki",
  "children": [
    {
      "type": "page",
      "name": "CodeWiki System Overview",
      "url": "/"
    },
    {
      "type": "folder",
      "name": "Overview",
      "children": [
        {
          "type": "page",
          "name": "CodeWiki System Overview",
          "url": "/"
        }
      ]
    },
    {
      "type": "folder",
      "name": "Architecture",
      "children": [
        {
          "type": "page",
          "name": "Setup & Getting Started",
          "url": "/setup"
        },
        {
          "type": "page",
          "name": "System Architecture Overview",
          "url": "/system-architecture"
        },
        {
          "type": "page",
          "name": "Command Line Interface (CLI)",
          "url": "/cli"
        },
        {
          "type": "page",
          "name": "Testing & Quality Assurance Overview",
          "url": "/testing"
        },
        {
          "type": "page",
          "name": "Deployment & Release",
          "url": "/deployment"
        },
        {
          "type": "page",
          "name": "Framework Endpoint Detection Test Strategies",
          "url": "/framework-endpoint-detection-test-strategies"
        },
        {
          "type": "page",
          "name": "Chatbot Indexing and Corpus Management",
          "url": "/chatbot-indexing-corpus-management"
        },
        {
          "type": "page",
          "name": "Chatbot Query Service Testing and Coverage",
          "url": "/chatbot-query-service-testing-and-coverage"
        },
        {
          "type": "page",
          "name": "Page Generation Pipeline Overview",
          "url": "/page-generation"
        },
        {
          "type": "page",
          "name": "Repository Scanning & Analysis Overview",
          "url": "/repository-analysis"
        },
        {
          "type": "page",
          "name": "Pipeline State Management Testing",
          "url": "/pipeline-state-management-testing"
        },
        {
          "type": "page",
          "name": "Evidence Assembly Workflow in Page Generation",
          "url": "/evidence-assembly-workflow"
        },
        {
          "type": "page",
          "name": "Repository Scanning Workflow and the RepoScan Class",
          "url": "/repository-scanning-workflow-reposcan-class"
        },
        {
          "type": "page",
          "name": "LLM Prompt Templates Overview",
          "url": "/llm-prompt-templates"
        },
        {
          "type": "page",
          "name": "Topic & Context Classification Overview",
          "url": "/topic-classification"
        },
        {
          "type": "page",
          "name": "Smart Update and Incremental Documentation Refresh",
          "url": "/smart-update-incremental-refresh"
        },
        {
          "type": "page",
          "name": "File Evidence Card Construction and Summarization",
          "url": "/file-evidence-card-construction"
        },
        {
          "type": "page",
          "name": "Repository File Classification and Context Summarization",
          "url": "/repository-file-classification-context-summarization"
        },
        {
          "type": "page",
          "name": "Prompt Template Planning and Generation Workflow",
          "url": "/prompt-template-planning-generation-workflow"
        },
        {
          "type": "page",
          "name": "DocBucket and DocPlan: Organizing and Representing Documentation Topics",
          "url": "/docbucket-docplan-organization"
        },
        {
          "type": "page",
          "name": "Documentation Bucketization Overview",
          "url": "/bucketization"
        },
        {
          "type": "page",
          "name": "Command-Line Interface and System Operations",
          "url": "/cli-system-operations"
        },
        {
          "type": "page",
          "name": "Source Context and Priority Determination",
          "url": "/source-context-priority"
        },
        {
          "type": "page",
          "name": "Documentation Planning with DocBucket and DocPlan",
          "url": "/documentation-planning-docbucket-docplan"
        },
        {
          "type": "page",
          "name": "DocPlan and DocBucket: Template Structure and Organization",
          "url": "/docplan-docbucket-template-structure-organization"
        },
        {
          "type": "page",
          "name": "RepoScan: Scanning and Extracting Context from Code Repositories",
          "url": "/reposcan-context-extraction"
        },
        {
          "type": "page",
          "name": "DocBucket and Documentation Planning Workflow",
          "url": "/docbucket-planning-workflow"
        },
        {
          "type": "page",
          "name": "Tracking and Ownership of Repository Files",
          "url": "/tracking-ownership-repository-files"
        },
        {
          "type": "page",
          "name": "Repository Scanning and Context Summarization for Prompt Templates",
          "url": "/repository-scanning-context-summarization-prompt-templates"
        },
        {
          "type": "page",
          "name": "Context Summarization: Identifying and Summarizing Documentation and Notebook Contexts",
          "url": "/context-summarization"
        },
        {
          "type": "page",
          "name": "Evidence Assembly and File Evidence Cards",
          "url": "/evidence-assembly-file-cards"
        },
        {
          "type": "page",
          "name": "Bucket and Endpoint File Tracking Utilities",
          "url": "/bucket-endpoint-file-tracking"
        },
        {
          "type": "page",
          "name": "Repository Scanning and Bucket File Tracking",
          "url": "/repo-scan-bucket-file-tracking"
        },
        {
          "type": "page",
          "name": "Context Summarization for Documentation and Notebooks",
          "url": "/context-summarization-doc-notebooks"
        },
        {
          "type": "page",
          "name": "Development Notes",
          "url": "/development-notes"
        }
      ]
    },
    {
      "type": "folder",
      "name": "Integrations",
      "children": [
        {
          "type": "page",
          "name": "Anthropic Integration Overview",
          "url": "/integration-anthropic"
        },
        {
          "type": "page",
          "name": "CodeWiki Chat Integration Overview",
          "url": "/integration-codewiki-chat"
        },
        {
          "type": "page",
          "name": "CodeWiki Embed Integration Overview",
          "url": "/integration-codewiki-embed"
        },
        {
          "type": "page",
          "name": "Vinculum Warehouse Management Integration Overview",
          "url": "/integration-vinculum"
        },
        {
          "type": "page",
          "name": "Webhook Integrations Overview",
          "url": "/integration-webhook"
        },
        {
          "type": "page",
          "name": "Chatbot Service Layer and Query Processing",
          "url": "/chatbot-service-query-processing"
        },
        {
          "type": "page",
          "name": "Anthropic LLM API Client Integration",
          "url": "/anthropic-llm-api-client-integration"
        },
        {
          "type": "page",
          "name": "Chatbot Backend Scaffold and API Integration",
          "url": "/chatbot-backend-scaffold-api-integration"
        },
        {
          "type": "page",
          "name": "CodeWiki Embed CLI Workflows",
          "url": "/cli-workflows"
        },
        {
          "type": "page",
          "name": "Warehouse API Endpoint Discovery and Planning",
          "url": "/warehouse-api-endpoint-discovery-planning"
        },
        {
          "type": "page",
          "name": "Webhook Event Processing Workflow",
          "url": "/webhook-event-processing-workflow"
        },
        {
          "type": "page",
          "name": "Anthropic Integration Configuration Management",
          "url": "/anthropic-integration-configuration-management"
        },
        {
          "type": "page",
          "name": "Chatbot Configuration Management and Settings",
          "url": "/chatbot-configuration-management-settings"
        },
        {
          "type": "page",
          "name": "Chatbot Backend Scaffolding and Configuration",
          "url": "/chatbot-backend-scaffolding-configuration"
        },
        {
          "type": "page",
          "name": "Symbol Clustering and Analysis for Vinculum Integration",
          "url": "/symbol-clustering-analysis-vinculum-integration"
        },
        {
          "type": "page",
          "name": "Webhook Integration Configuration and Security",
          "url": "/webhook-integration-configuration-security"
        },
        {
          "type": "page",
          "name": "Pipeline Architecture and Documentation Generation",
          "url": "/pipeline-architecture-doc-generation"
        },
        {
          "type": "page",
          "name": "CLI Commands for Anthropic Integration",
          "url": "/cli-commands-for-anthropic-integration"
        },
        {
          "type": "page",
          "name": "CodeWiki Chat CLI Commands and Workflow",
          "url": "/codewiki-chat-cli-commands-workflow"
        },
        {
          "type": "page",
          "name": "LLM Client Integration for Embedding APIs",
          "url": "/llm-client-embedding-api"
        },
        {
          "type": "page",
          "name": "Endpoint Bundling and Evidence Management",
          "url": "/endpoint-bundling-evidence-management"
        },
        {
          "type": "page",
          "name": "Embedding and LLM Client Integration for Webhooks",
          "url": "/embedding-llm-client-integration-webhooks"
        },
        {
          "type": "page",
          "name": "LLM-Driven Symbol Clustering and Analysis Workflow",
          "url": "/llm-driven-symbol-clustering-analysis-workflow"
        },
        {
          "type": "page",
          "name": "Symbol Clustering and Endpoint Analysis for Chat Integration",
          "url": "/symbol-clustering-endpoint-analysis-chat-integration"
        },
        {
          "type": "page",
          "name": "Persistence and State Management for Webhook Workflows",
          "url": "/persistence-state-management-webhook-workflows"
        }
      ]
    },
    {
      "type": "folder",
      "name": "Operations",
      "children": [
        {
          "type": "page",
          "name": "Configuration Reference",
          "url": "/configuration"
        }
      ]
    },
    {
      "type": "folder",
      "name": "Data Layer",
      "children": [
        {
          "type": "page",
          "name": "Database Models & Persistence Overview",
          "url": "/database"
        },
        {
          "type": "page",
          "name": "Database Persistence Strategies and State Management",
          "url": "/database-persistence-strategies-state-management"
        },
        {
          "type": "page",
          "name": "Corpus and Vector Index Persistence for Chatbot",
          "url": "/chatbot-corpus-vector-index-persistence"
        },
        {
          "type": "page",
          "name": "Manifest Management and File Tracking",
          "url": "/manifest-management-file-tracking"
        },
        {
          "type": "page",
          "name": "Schema Analysis and Symbol Clustering",
          "url": "/schema-analysis-symbol-clustering"
        },
        {
          "type": "page",
          "name": "Config and Database Signal Extraction for Documentation",
          "url": "/config-database-signal-extraction"
        },
        {
          "type": "page",
          "name": "Source Context and Signal Generation",
          "url": "/source-context-signal-generation"
        }
      ]
    },
    {
      "type": "folder",
      "name": "API",
      "children": [
        {
          "type": "page",
          "name": "Health & Query API Family",
          "url": "/api-family-health-query"
        },
        {
          "type": "page",
          "name": "User Management API Family",
          "url": "/api-family-users"
        },
        {
          "type": "page",
          "name": "Authentication API Family",
          "url": "/api-family-auth"
        },
        {
          "type": "page",
          "name": "Admin & Reporting API Family",
          "url": "/api-family-admin-stats"
        },
        {
          "type": "page",
          "name": "POST /query",
          "url": "/post-query"
        },
        {
          "type": "page",
          "name": "GET /login",
          "url": "/get-login"
        },
        {
          "type": "page",
          "name": "POST /login",
          "url": "/post-login"
        },
        {
          "type": "page",
          "name": "GET /api/v1/users",
          "url": "/get-api-v1-users"
        },
        {
          "type": "page",
          "name": "POST /api/v1/users",
          "url": "/post-api-v1-users"
        },
        {
          "type": "page",
          "name": "GET /api/v1/admin/stats",
          "url": "/get-api-v1-admin-stats"
        },
        {
          "type": "page",
          "name": "GET /reports/{slug}",
          "url": "/get-reports-slug"
        },
        {
          "type": "page",
          "name": "GET /api/users",
          "url": "/get-api-users"
        },
        {
          "type": "page",
          "name": "POST /api/users",
          "url": "/post-api-users"
        },
        {
          "type": "page",
          "name": "GET /api/users/{id}",
          "url": "/get-api-users-id"
        },
        {
          "type": "page",
          "name": "DELETE /api/users/{id}",
          "url": "/delete-api-users-id"
        },
        {
          "type": "page",
          "name": "GET /api/users/{id}/stats",
          "url": "/get-api-users-id-stats"
        }
      ]
    }
  ]
};
