// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/deepdoc-landing/ChangelogPage.tsx": () => import("../components/mockups/deepdoc-landing/ChangelogPage.tsx"),
  "./components/mockups/deepdoc-landing/DeepDocCanvas.tsx": () => import("../components/mockups/deepdoc-landing/DeepDocCanvas.tsx"),
  "./components/mockups/deepdoc-landing/DocsPage.tsx": () => import("../components/mockups/deepdoc-landing/DocsPage.tsx"),
  "./components/mockups/deepdoc-landing/LandingPage.tsx": () => import("../components/mockups/deepdoc-landing/LandingPage.tsx")
};
