"""Legacy data types from planner v1 — kept for backward compatibility.

Used by persistence_v2.py (loading old plans) and updater_v2.py (legacy update path).
"""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass
class DocPage:
    """A single page in the planned documentation (v1 format)."""

    title: str
    slug: str
    page_type: str
    description: str
    source_files: list[str]
    section: str = ""
    priority: int = 0
    depends_on: list[str] = field(default_factory=list)


@dataclass
class DocPlan:
    """Complete doc plan generated by the AI (v1 format)."""

    pages: list[DocPage]
    nav_structure: dict[str, list[str]]
    skipped_files: list[str]
    orphaned_files: list[str] = field(default_factory=list)


@dataclass
class RepoScan:
    """Output of the scan phase (v1 format)."""

    file_tree: dict[str, list[str]]
    file_summaries: dict[str, str]
    api_endpoints: list[dict]
    languages: dict[str, int]
    has_openapi: bool
    openapi_paths: list[str]
    total_files: int
    frameworks_detected: list[str]
    entry_points: list[str]
    config_files: list[str]
