"""Authored-document classification and documentation-system detection.

Slice 11: Document role classifier — distinguishes authored docs, docs-system
configs, generated references, built output, and AI-derived exports.

Slice 12: DocumentationSystem model — detects and models existing documentation
systems (MkDocs/Zensical first, then Docusaurus/Sphinx/Mintlify/Fumadocs).

All detection is high-confidence only — no "AI writing style" heuristics.
Files with uncertain provenance are classified as ``unknown_generated`` and
inventoried but not used as factual evidence.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

# ---------------------------------------------------------------------------
# Document roles (Slice 11)
# ---------------------------------------------------------------------------


class DocRole:
    AUTHORED = "authored_docs"
    DOCS_CONFIG = "docs_config"
    GENERATED_REF = "generated_ref"
    AI_DERIVED = "ai_derived_export"
    BUILT_SITE = "built_docs_site"
    UNKNOWN = "unknown_generated"

    ALL = {AUTHORED, DOCS_CONFIG, GENERATED_REF, AI_DERIVED, BUILT_SITE, UNKNOWN}


def classify_doc_role(
    rel_path: str,
    content: str = "",
    *,
    source_kind: str = "product",
    output_dir: str = "",
    site_dir: str = "",
) -> str:
    """Classify a file discovered by the scan walk into a doc role.

    Returns one of ``DocRole.*`` constants.  Files that are not documentation
    at all return an empty string (caller should fall back to their normal
    source-kind classification).
    """
    normalized = rel_path.replace("\\", "/").strip("/")
    lowered = normalized.lower()
    parts = [part for part in lowered.split("/") if part]
    fname = parts[-1] if parts else lowered

    if output_dir and (
        lowered == output_dir.lower() or lowered.startswith(output_dir.lower() + "/")
    ):
        return _classify_generated_output_root(rel_path, content)

    if site_dir and (
        lowered == site_dir.lower() or lowered.startswith(site_dir.lower() + "/")
    ):
        return DocRole.BUILT_SITE

    if (
        lowered == "site" or lowered.startswith("site/")
    ) and source_kind not in ("generated",):
        return DocRole.BUILT_SITE

    if source_kind in ("generated",):
        return DocRole.UNKNOWN

    if _is_docs_config(fname, lowered, content):
        return DocRole.DOCS_CONFIG

    if content and _is_ai_derived(content):
        return DocRole.AI_DERIVED

    if _is_generated_ref(lowered, fname, content):
        return DocRole.GENERATED_REF

    if (
        lowered.startswith("docs/")
        and fname.endswith((".md", ".mdx", ".txt"))
        and not _is_deepdoc_owned(content)
    ):
        return DocRole.AUTHORED

    if lowered.startswith("docs_src/") and fname.endswith((".py", ".js", ".ts", ".tsx")):
        return DocRole.AUTHORED

    if fname in _AUTHORED_FILENAMES and not _is_deepdoc_owned(content):
        return DocRole.AUTHORED

    return ""


def _is_docs_config(fname: str, lowered: str, content: str) -> bool:
    """Return True for docs-system configuration files."""
    return fname in {
        "mkdocs.yml",
        "mkdocs.yaml",
        "docusaurus.config.js",
        "docusaurus.config.ts",
        "conf.py",
        "mint.json",
    } or (
        "mkdocs" in fname
        and fname.endswith((".yml", ".yaml"))
        and ("inherit" in content.lower()[:500] or "site_name" in content.lower()[:500])
    )


def _is_ai_derived(content: str) -> bool:
    """Return True when content has high-confidence AI-generated provenance.

    Only exact frontmatter/provenance markers are trusted, never prose style.
    """
    header = content[:2000]
    if "deepdoc_generated_version:" in header or "deepdoc_generated_at:" in header:
        return True
    if "deepwiki.com/" in header:
        return True
    if "_generated_by" in header and "deepdoc" in header.lower():
        return True
    return False


def _is_generated_ref(lowered: str, fname: str, content: str) -> bool:
    """Return True for generated API/SDK reference output."""
    if any(
        seg in lowered
        for seg in ("_build/", "api/generated", "sdk/generated", "typedoc-output")
    ):
        return True
    if fname.endswith(".html") and "generated by" in content[:500].lower():
        return True
    return False


def _is_deepdoc_owned(content: str) -> bool:
    """Return True when content has DeepDoc provenance frontmatter."""
    return "deepdoc_generated_version:" in content[:2000]


def _classify_generated_output_root(rel_path: str, content: str) -> str:
    """Files below the configured output directory are either DeepDoc-owned or unknown."""
    if _is_deepdoc_owned(content):
        return DocRole.AI_DERIVED
    return DocRole.UNKNOWN


_AUTHORED_FILENAMES = {
    "readme.md",
    "readme.mdx",
    "changelog.md",
    "history.md",
    "design.md",
    "architecture.md",
    "glossary.md",
    "notes.md",
    "experiments.md",
    "contributing.md",
    "code_of_conduct.md",
    "security.md",
    "release-notes.md",
}


# ---------------------------------------------------------------------------
# DocumentationSystem model (Slice 12)
# ---------------------------------------------------------------------------


@dataclass
class DocumentationSystem:
    """A detected repository documentation system."""

    kind: str = "none"  # "mkdocs_zensical", "docusaurus", "sphinx", "mintlify", "fumadocs", "none"
    detected: bool = False
    source_roots: list[str] = field(default_factory=list)
    config_files: list[str] = field(default_factory=list)
    build_tools: list[str] = field(default_factory=list)
    translation_roots: list[str] = field(default_factory=list)
    example_roots: list[str] = field(default_factory=list)
    build_output_dirs: list[str] = field(default_factory=list)
    ci_workflows: list[str] = field(default_factory=list)
    deploy_workflows: list[str] = field(default_factory=list)
    release_note_paths: list[str] = field(default_factory=list)
    generated_ref_roots: list[str] = field(default_factory=list)
    authored_nav: dict[str, Any] | None = None


def detect_docs_system(
    repo_root: Path,
    file_tree: dict[str, list[str]],
    file_contents: dict[str, str],
    source_kind_by_file: dict[str, str],
    doc_role_by_file: dict[str, str],
    config_files: list[str],
    ci_artifacts: list[str] | None = None,
) -> DocumentationSystem:
    """Detect existing documentation systems in a repository.

    Returns ``DocumentationSystem(detected=False)`` when no known system is found.
    """
    system = _detect_mkdocs(
        repo_root, file_tree, file_contents, source_kind_by_file, doc_role_by_file,
        config_files, ci_artifacts,
    )
    if system and system.detected:
        return system

    system = _detect_docusaurus(
        file_tree, file_contents, doc_role_by_file, config_files,
    )
    if system and system.detected:
        return system

    return DocumentationSystem()


def _detect_mkdocs(
    repo_root: Path,
    file_tree: dict[str, list[str]],
    file_contents: dict[str, str],
    source_kind_by_file: dict[str, str],
    doc_role_by_file: dict[str, str],
    config_files: list[str],
    ci_artifacts: list[str] | None,
) -> DocumentationSystem | None:
    """Detect MkDocs/Zensical documentation systems (FastAPI's system)."""
    system = DocumentationSystem(kind="mkdocs_zensical")

    mkdocs_configs = [
        rel
        for rel in file_contents
        if Path(rel).name in ("mkdocs.yml", "mkdocs.yaml")
        and doc_role_by_file.get(rel) == DocRole.DOCS_CONFIG
    ]
    if not mkdocs_configs:
        return None

    system.detected = True
    system.config_files = mkdocs_configs

    for rel in mkdocs_configs:
        parent = str(Path(rel).parent)
        if "/" + parent + "/" not in str(mkdocs_configs):
            candidate = parent + "/docs"
            if any(
                d == candidate or d.startswith(candidate + "/")
                for d in file_contents
                if doc_role_by_file.get(d) == DocRole.AUTHORED
            ):
                system.source_roots.append(candidate)

    translation_dirs: set[str] = set()
    for d in file_tree:
        for fname in file_tree[d]:
            if fname in ("mkdocs.yml", "mkdocs.yaml"):
                parent_dir = d if d != "." else ""
                if parent_dir and parent_dir.count("/") >= 1:
                    translation_dirs.add(parent_dir)
    for td in sorted(translation_dirs):
        parts = td.split("/")
        if len(parts) >= 2 and parts[0] == "docs":
            system.translation_roots.append(td)

    for rel in file_contents:
        if "stage_zensical" in file_contents[rel][:5000]:
            system.build_tools.append(rel)

    for rel, content in file_contents.items():
        lower_content = content.lower()
        if rel.startswith("docs/") and rel.endswith(".py"):
            if any(kw in lower_content for kw in ("stage_zensical", "mkdocs", "build_all")):
                system.build_tools.append(rel)

    for rel in file_tree.get(".", []) + file_tree.get("docs_src", []):
        if "docs_src" in rel:
            pass
    for rel in file_contents:
        if rel.startswith("docs_src/"):
            system.example_roots.append(str(Path(rel).parent))
    system.example_roots = sorted(set(system.example_roots))[:10]

    if ci_artifacts:
        for artifact in ci_artifacts:
            if "build-docs" in artifact.lower() or "deploy-docs" in artifact.lower():
                content = file_contents.get(artifact, "")
                if "build" in artifact.lower() or ("mkdocs" in content.lower()[:2000] and "build" in content.lower()[:2000]):
                    system.ci_workflows.append(artifact)
                elif "deploy" in artifact.lower():
                    system.deploy_workflows.append(artifact)

    for rel in file_contents:
        if rel.endswith("release-notes.md") or rel.endswith("changelog.md"):
            system.release_note_paths.append(rel)

    system.build_output_dirs = sorted(
        d
        for d in ("site", "site_zensical_src")
        if any(
            path == d or path.startswith(d + "/")
            for path in file_contents
        )
    )

    return system


def _detect_docusaurus(
    file_tree: dict[str, list[str]],
    file_contents: dict[str, str],
    doc_role_by_file: dict[str, str],
    config_files: list[str],
) -> DocumentationSystem | None:
    """Detect Docusaurus documentation systems."""
    docusaurus_configs = [
        rel
        for rel in file_contents
        if Path(rel).name in ("docusaurus.config.js", "docusaurus.config.ts")
        and doc_role_by_file.get(rel) == DocRole.DOCS_CONFIG
    ]
    if not docusaurus_configs:
        return None

    system = DocumentationSystem(kind="docusaurus")
    system.detected = True
    system.config_files = docusaurus_configs

    for rel in docusaurus_configs:
        parent = str(Path(rel).parent)
        docs_dir = parent + "/docs" if parent else "docs"
        if any(
            d == docs_dir or d.startswith(docs_dir + "/")
            for d in file_contents
            if doc_role_by_file.get(d) == DocRole.AUTHORED
        ):
            system.source_roots.append(docs_dir)

    return system


__all__ = [
    "DocRole",
    "classify_doc_role",
    "DocumentationSystem",
    "detect_docs_system",
    "_is_ai_derived",
    "_is_deepdoc_owned",
]