"""Shared data models for the bucket-based v2 pipeline."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Any

from .parser.base import ParsedFile

if TYPE_CHECKING:
    from .call_graph import CallGraph
    from .scanner import DebugSignal


@dataclass
class DocBucket:
    """A single documentation bucket, the core planning unit in v2."""

    bucket_type: str
    title: str
    slug: str
    section: str
    description: str
    depends_on: list[str] = field(default_factory=list)
    owned_files: list[str] = field(default_factory=list)
    owned_symbols: list[str] = field(default_factory=list)
    artifact_refs: list[str] = field(default_factory=list)
    required_sections: list[str] = field(default_factory=list)
    required_diagrams: list[str] = field(default_factory=list)
    coverage_targets: list[str] = field(default_factory=list)
    generation_hints: dict[str, Any] = field(default_factory=dict)
    priority: int = 0
    parent_slug: str | None = None
    publication_tier: str = "core"
    source_kind_summary: dict[str, int] = field(default_factory=dict)


@dataclass
class DocPlan:
    """Complete doc plan generated by the multi-step planner."""

    buckets: list[DocBucket]
    nav_structure: dict[str, list[str]]
    skipped_files: list[str]
    orphaned_files: list[str] = field(default_factory=list)
    classification: dict[str, Any] = field(default_factory=dict)
    integration_candidates: list[dict] = field(default_factory=list)

    @property
    def pages(self) -> list[_BucketAsPage]:
        """Shim so legacy callers can treat buckets like old pages."""
        return [_BucketAsPage(bucket) for bucket in self.buckets]


class _BucketAsPage:
    """Adapter so DocBucket still looks like the legacy DocPage shape."""

    def __init__(self, bucket: DocBucket):
        self._b = bucket

    @property
    def title(self):
        return self._b.title

    @property
    def slug(self):
        return self._b.slug

    @property
    def page_type(self):
        return self._b.generation_hints.get("prompt_style", self._b.bucket_type)

    @property
    def description(self):
        return self._b.description

    @property
    def source_files(self):
        return self._b.owned_files

    @source_files.setter
    def source_files(self, val):
        self._b.owned_files = val

    @property
    def section(self):
        return self._b.section

    @property
    def priority(self):
        return self._b.priority

    @property
    def depends_on(self):
        return self._b.depends_on


@dataclass
class RepoScan:
    """Output of the scan phase before LLM planning begins."""

    file_tree: dict[str, list[str]]
    file_summaries: dict[str, str]
    api_endpoints: list[dict]
    languages: dict[str, int]
    has_openapi: bool
    openapi_paths: list[str]
    total_files: int
    frameworks_detected: list[str]
    entry_points: list[str]
    config_files: list[str]
    file_line_counts: dict[str, int] = field(default_factory=dict)
    parsed_files: dict[str, ParsedFile] = field(default_factory=dict)
    file_contents: dict[str, str] = field(default_factory=dict)
    giant_file_clusters: dict[str, Any] = field(default_factory=dict)
    endpoint_bundles: list[Any] = field(default_factory=list)
    integration_identities: list[Any] = field(default_factory=list)
    artifact_scan: Any = None
    runtime_scan: Any = None
    graphql_interfaces: list[Any] = field(default_factory=list)
    knex_artifacts: list[Any] = field(default_factory=list)
    doc_contexts: dict[str, str] = field(default_factory=dict)
    research_contexts: list[dict[str, Any]] = field(default_factory=list)
    topic_candidates: list[dict[str, Any]] = field(default_factory=list)
    semantic_file_token_cache: dict[str, set[str]] = field(default_factory=dict)
    topic_file_token_cache: dict[str, set[str]] = field(default_factory=dict)
    topic_context_token_cache: dict[str, set[str]] = field(default_factory=dict)
    planner_timings: dict[str, float] = field(default_factory=dict)
    source_kind_by_file: dict[str, str] = field(default_factory=dict)
    file_frameworks: dict[str, list[str]] = field(default_factory=dict)
    config_impacts: list[dict[str, Any]] = field(default_factory=list)
    call_graph: CallGraph | None = None
    debug_signals: list[DebugSignal] = field(default_factory=list)

    @property
    def published_api_endpoints(self) -> list[dict[str, Any]]:
        return [ep for ep in self.api_endpoints if ep.get("publication_ready", True)]


def tracked_bucket_files(bucket: DocBucket) -> list[str]:
    """Return all repo files whose changes should invalidate this bucket."""
    return sorted({f for f in [*bucket.owned_files, *bucket.artifact_refs] if f})


def endpoint_owned_files(endpoint: dict[str, Any]) -> list[str]:
    """Return route and handler ownership for an endpoint record."""
    files = [
        endpoint.get("route_file", ""),
        endpoint.get("handler_file", ""),
        endpoint.get("file", ""),
    ]
    return sorted({f for f in files if f})


__all__ = [
    "DocBucket",
    "DocPlan",
    "RepoScan",
    "_BucketAsPage",
    "tracked_bucket_files",
    "endpoint_owned_files",
]
