from .common import *


def _package_json(project_name: str) -> str:
    return (
        json.dumps(
            {
                "name": f"{project_name.lower().replace(' ', '-')}-docs",
                "private": True,
                "type": "module",
                "scripts": {
                    "dev": "next dev",
                    "build": "next build",
                    "start": "next dev",
                },
                "dependencies": {
                    "@orama/orama": "^3.1.10",
                    "@types/mdx": "^2.0.13",
                    "fumadocs-core": "15.7.9",
                    "fumadocs-mdx": "11.9.0",
                    "fumadocs-openapi": "9.3.9",
                    "fumadocs-ui": "15.7.11",
                    "mermaid": "^11.6.0",
                    "next": "15.3.0",
                    "next-themes": "0.4.6",
                    "react": "19.1.0",
                    "react-dom": "19.1.0",
                    "react-markdown": "^10.1.0",
                    "react-syntax-highlighter": "^15.6.1",
                    "tailwindcss": "^4.1.3",
                },
                "devDependencies": {
                    "@tailwindcss/postcss": "^4.1.14",
                    "@types/node": "^22.13.9",
                    "@types/react": "^19.0.12",
                    "@types/react-dom": "^19.0.4",
                    "@types/react-syntax-highlighter": "^15.5.13",
                    "typescript": "^5.8.2",
                },
            },
            indent=2,
        )
        + "\n"
    )


def _tsconfig_json() -> str:
    return (
        json.dumps(
            {
                "compilerOptions": {
                    "target": "ES2022",
                    "lib": ["dom", "dom.iterable", "es2022"],
                    "allowJs": False,
                    "skipLibCheck": True,
                    "strict": True,
                    "noEmit": True,
                    "esModuleInterop": True,
                    "module": "esnext",
                    "moduleResolution": "bundler",
                    "resolveJsonModule": True,
                    "isolatedModules": True,
                    "jsx": "preserve",
                    "incremental": True,
                    "baseUrl": ".",
                    "paths": {
                        "@/*": ["./*"],
                        "fumadocs-mdx:collections/*": [".source/*"],
                    },
                    "plugins": [{"name": "next"}],
                },
                "include": [
                    "next-env.d.ts",
                    "**/*.ts",
                    "**/*.tsx",
                    ".next/types/**/*.ts",
                    ".source/**/*.ts",
                ],
                "exclude": ["node_modules"],
            },
            indent=2,
        )
        + "\n"
    )


def _postcss_config_mjs() -> str:
    return dedent(
        """\
        export default {
          plugins: {
            '@tailwindcss/postcss': {},
          },
        };
        """
    )


def _next_env_d_ts() -> str:
    return dedent(
        """\
        /// <reference types="next" />
        /// <reference types="next/image-types/global" />

        // This file is generated by Next.js. Do not edit manually.
        """
    )


def _next_config_mjs() -> str:
    return dedent(
        """\
        import path from 'node:path';
        import { fileURLToPath } from 'node:url';
        import { createMDX } from 'fumadocs-mdx/next';

        const __dirname = path.dirname(fileURLToPath(import.meta.url));
        const repoRoot = path.join(__dirname, '..');
        const withMDX = createMDX({
          configPath: './source.config.mjs',
        });
        const explicitBasePath = (process.env.DEEPDOC_SITE_BASE_PATH ?? '').trim();
        const normalizedExplicitBasePath = explicitBasePath
          ? `/${explicitBasePath.replace(/^\\/+|\\/+$/g, '')}`
          : '';
        const repository = process.env.GITHUB_REPOSITORY ?? '';
        const [, repoName = ''] = repository.split('/');
        const isUserSite = repoName.endsWith('.github.io');
        const githubPagesBasePath =
          process.env.GITHUB_PAGES === 'true' && repoName && !isUserSite
            ? `/${repoName}`
            : '';
        const siteBasePath = normalizedExplicitBasePath || githubPagesBasePath;
        const useTrailingSlash = process.env.GITHUB_PAGES === 'true' || Boolean(siteBasePath);

        /** @type {import('next').NextConfig} */
        const config = {
          reactStrictMode: true,
          output: 'export',
          trailingSlash: useTrailingSlash,
          basePath: siteBasePath || undefined,
          assetPrefix: siteBasePath || undefined,
          images: {
            unoptimized: true,
          },
          experimental: {
            externalDir: true,
          },
          outputFileTracingRoot: repoRoot,
        };

        export default withMDX(config);
        """
    )


def _source_config_mjs(docs_dir_relative: str) -> str:
    return dedent(
        f"""\
        import {{ defineDocs, defineConfig }} from 'fumadocs-mdx/config';
        import {{ remarkMdxMermaid }} from 'fumadocs-core/mdx-plugins';

        export const {{ docs, meta }} = defineDocs({{
          dir: '{docs_dir_relative}',
        }});

        export default defineConfig({{
          mdxOptions: {{
            remarkPlugins: [remarkMdxMermaid],
          }},
        }});
        """
    )


def _mdx_components_tsx(has_openapi: bool) -> str:
    api_import = (
        "import { APIPage } from '@/components/api-page';\n" if has_openapi else ""
    )
    api_component = "    APIPage,\n" if has_openapi else ""
    return dedent(
        f"""\
        import defaultMdxComponents from 'fumadocs-ui/mdx';
        import * as AccordionComponents from 'fumadocs-ui/components/accordion';
        import * as StepsComponents from 'fumadocs-ui/components/steps';
        import * as TabsComponents from 'fumadocs-ui/components/tabs';
        {api_import}import {{ Mermaid }} from '@/components/mdx/mermaid';
        import type {{ MDXComponents }} from 'mdx/types';

        export function getMDXComponents(components?: MDXComponents): MDXComponents {{
          return {{
            ...defaultMdxComponents,
            ...AccordionComponents,
            ...StepsComponents,
            ...TabsComponents,
{api_component}            Mermaid,
            ...components,
          }};
        }}

        export const useMDXComponents = getMDXComponents;
        """
    )


def _app_layout_tsx(project_name: str, chatbot_enabled: bool = False) -> str:
    chatbot_import = (
        "import { ChatbotToggle } from '@/components/chatbot-toggle';\n"
        if chatbot_enabled
        else ""
    )
    chatbot_mount = "          <ChatbotToggle />\n" if chatbot_enabled else ""
    return dedent(
        f"""\
        import './global.css';
        {chatbot_import}import {{ RootProvider }} from 'fumadocs-ui/provider';
        import type {{ Metadata }} from 'next';
        import type {{ ReactNode }} from 'react';

        export const metadata: Metadata = {{
          title: '{project_name}',
          description: 'Auto-generated developer documentation',
          icons: {{
            icon: 'favicon.svg',
          }},
        }};

        const siteBasePath = (process.env.NEXT_PUBLIC_DEEPDOC_SITE_BASE_PATH ?? '').replace(/\\/+$/, '');
        const searchApiPath = siteBasePath ? `${{siteBasePath}}/search` : '/search';

        export default function RootLayout({{
          children,
        }}: {{
          children: ReactNode;
        }}) {{
          return (
            <html lang="en" suppressHydrationWarning>
              <body className="min-h-screen bg-fd-background text-fd-foreground antialiased">
        <RootProvider
          search={{{{
            options: {{
              api: searchApiPath,
              type: 'static',
            }},
          }}}}
        >
                  {{children}}
{chatbot_mount}        </RootProvider>
              </body>
            </html>
          );
        }}
        """
    )


def _global_css(cfg: dict[str, Any]) -> str:
    site_cfg = cfg.get("site", {})
    site_colors = site_cfg.get("colors", {}) if isinstance(site_cfg, dict) else {}
    chatbot_enabled = bool(cfg.get("chatbot", {}).get("enabled"))
    primary = site_colors.get("primary") or "#EB3E25"
    light = site_colors.get("light") or "#EF624E"
    dark = site_colors.get("dark") or "#C1331F"

    base_css = dedent(
        """\
        @import 'tailwindcss';
        @import 'fumadocs-ui/css/neutral.css';
        @import 'fumadocs-ui/css/preset.css';
        @import 'fumadocs-openapi/css/preset.css';

        :root {
          --deepdoc-accent: __PRIMARY__;
          --deepdoc-brand-primary: __PRIMARY__;
          --deepdoc-brand-light: __LIGHT__;
          --deepdoc-brand-dark: __DARK__;
          --color-fd-primary: var(--deepdoc-brand-primary);
          --color-fd-primary-foreground: #fff7f4;
          --color-fd-ring: color-mix(in srgb, var(--deepdoc-brand-primary) 40%, white 60%);
        }

        body {
          font-feature-settings: 'liga' 1, 'calt' 1;
          background: var(--color-fd-background);
        }
        """
    )

    chatbot_css = dedent(
        """\

        .deepdoc-chatbot-shell {
          pointer-events: none;
          position: fixed;
          left: 50%;
          bottom: clamp(0.9rem, 2vw, 1.5rem);
          z-index: 60;
          width: min(56rem, calc(100vw - 2rem));
          transform: translateX(-50%);
          opacity: 1;
          will-change: transform, opacity;
          transition:
            transform 320ms cubic-bezier(0.22, 1, 0.36, 1),
            opacity 260ms ease;
        }

        .deepdoc-chatbot-shell--visible {
          opacity: 1;
          transform: translateX(-50%);
        }

        .deepdoc-chatbot-shell--hidden {
          opacity: 0.01;
          transform: translate(-50%, calc(100% + 1rem));
        }

        .deepdoc-chatbot-shell--hidden .deepdoc-chatbot-dock {
          pointer-events: none;
          transform: translateY(0.7rem) scale(0.985);
          filter: blur(6px);
        }

        .deepdoc-chatbot-dock {
          pointer-events: auto;
          border: 1px solid color-mix(in srgb, var(--deepdoc-brand-light) 8%, var(--color-fd-border) 92%);
          border-radius: 1.4rem;
          padding: 0.9rem;
          background: color-mix(in srgb, white 98.5%, var(--deepdoc-brand-light) 1.5%);
          box-shadow:
            0 10px 28px rgba(131, 39, 25, 0.05),
            0 4px 10px rgba(235, 62, 37, 0.025);
          backdrop-filter: blur(8px);
          transform-origin: center bottom;
          will-change: transform, filter;
          transition:
            transform 320ms cubic-bezier(0.22, 1, 0.36, 1),
            filter 220ms ease,
            box-shadow 220ms ease,
            border-color 220ms ease;
        }

        @media (prefers-reduced-motion: reduce) {
          .deepdoc-chatbot-shell,
          .deepdoc-chatbot-dock {
            transition: none;
          }
        }

        .deepdoc-chatbot-dock__meta {
          display: flex;
          align-items: center;
          justify-content: space-between;
          gap: 1rem;
          margin-bottom: 0.75rem;
        }

        .deepdoc-chatbot-dock__eyebrow {
          display: inline-flex;
          align-items: center;
          gap: 0.5rem;
          font-size: 0.76rem;
          font-weight: 600;
          letter-spacing: 0.08em;
          text-transform: uppercase;
          color: color-mix(in srgb, var(--deepdoc-brand-dark) 70%, var(--color-fd-muted-foreground) 30%);
        }

        .deepdoc-chatbot-dock__eyebrow::before {
          content: '';
          height: 0.45rem;
          width: 0.45rem;
          border-radius: 999px;
          background: color-mix(in srgb, var(--deepdoc-brand-primary) 72%, white 28%);
          box-shadow: 0 0 0 0.18rem color-mix(in srgb, var(--deepdoc-brand-light) 8%, white 92%);
        }

        .deepdoc-chatbot-dock__hint {
          max-width: 22rem;
          font-size: 0.84rem;
          color: color-mix(in srgb, var(--color-fd-muted-foreground) 82%, transparent 18%);
          text-align: right;
        }

        .deepdoc-chatbot-mode-toggle {
          border: 1px solid color-mix(in srgb, var(--deepdoc-brand-light) 12%, var(--color-fd-border) 88%);
          border-radius: 999px;
          padding: 0.45rem 0.8rem;
          font-size: 0.84rem;
          font-weight: 600;
          color: var(--color-fd-muted-foreground);
          background: color-mix(in srgb, white 90%, var(--deepdoc-brand-light) 10%);
          transition: background 160ms ease, color 160ms ease, border-color 160ms ease;
        }

        .deepdoc-chatbot-mode-toggle--active {
          border-color: color-mix(in srgb, var(--deepdoc-brand-primary) 42%, var(--color-fd-border) 58%);
          color: var(--deepdoc-brand-dark);
          background: color-mix(in srgb, white 72%, var(--deepdoc-brand-light) 28%);
        }

        .deepdoc-chatbot-dock__row {
          display: grid;
          grid-template-columns: minmax(0, 1fr) auto;
          gap: 0.8rem;
          align-items: end;
        }

        .deepdoc-chatbot-dock__input,
        .deepdoc-chatbot-panel__input,
        .deepdoc-chatbot-panel__button {
          border: 1px solid color-mix(in srgb, var(--deepdoc-brand-light) 8%, var(--color-fd-border) 92%);
        }

        .deepdoc-chatbot-dock__input,
        .deepdoc-chatbot-panel__input {
          min-height: 5rem;
          resize: vertical;
          border-radius: 1rem;
          background: white;
          padding: 0.95rem 1rem;
          color: var(--color-fd-foreground);
          box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.7);
        }

        .deepdoc-chatbot-dock__input:focus,
        .deepdoc-chatbot-panel__input:focus {
          outline: 2px solid color-mix(in srgb, var(--deepdoc-brand-light) 24%, white 76%);
          outline-offset: 2px;
        }

        .deepdoc-chatbot-dock__submit,
        .deepdoc-chatbot-panel__button {
          border-radius: 999px;
          padding: 0.9rem 1.25rem;
          background: linear-gradient(135deg, var(--deepdoc-brand-light), var(--deepdoc-brand-primary) 58%, var(--deepdoc-brand-dark));
          color: white;
          box-shadow: 0 10px 22px rgba(193, 51, 31, 0.12);
          transition: transform 160ms ease, box-shadow 160ms ease, filter 160ms ease;
        }

        .deepdoc-chatbot-dock__submit:hover:not(:disabled),
        .deepdoc-chatbot-panel__button:hover:not(:disabled) {
          transform: translateY(-1px);
          box-shadow: 0 14px 28px rgba(193, 51, 31, 0.16);
          filter: saturate(1.04);
        }

        .deepdoc-chatbot-dock__submit:disabled,
        .deepdoc-chatbot-panel__button:disabled {
          cursor: wait;
          opacity: 0.74;
        }

        .deepdoc-chatbot-page {
          width: min(76rem, calc(100vw - 2.5rem));
          margin: 0 auto;
          padding: 2.4rem 0 11rem;
        }

        .deepdoc-chatbot-page__back {
          display: inline-flex;
          align-items: center;
          gap: 0.5rem;
          font-size: 0.95rem;
          color: var(--color-fd-muted-foreground);
          text-decoration: none;
        }

        .deepdoc-chatbot-page__back:hover {
          color: var(--deepdoc-brand-dark);
        }

        .deepdoc-chatbot-page__hero {
          display: flex;
          flex-wrap: wrap;
          align-items: flex-end;
          justify-content: space-between;
          gap: 1rem;
          margin: 1rem 0 1.4rem;
        }

        .deepdoc-chatbot-page__eyebrow {
          margin: 0 0 0.45rem;
          font-size: 0.82rem;
          font-weight: 700;
          letter-spacing: 0.08em;
          text-transform: uppercase;
          color: var(--deepdoc-brand-dark);
        }

        .deepdoc-chatbot-page__hero h1 {
          margin: 0;
          max-width: 40rem;
          font-size: clamp(2rem, 3vw, 3rem);
          line-height: 1.04;
          letter-spacing: -0.04em;
          color: #25110d;
        }

        .deepdoc-chatbot-page__hero p {
          margin: 0.65rem 0 0;
          max-width: 38rem;
          color: var(--color-fd-muted-foreground);
        }

        .deepdoc-chatbot-page__chip {
          display: inline-flex;
          align-items: center;
          border: 1px solid color-mix(in srgb, var(--deepdoc-brand-light) 14%, var(--color-fd-border) 86%);
          border-radius: 999px;
          padding: 0.5rem 0.8rem;
          font-size: 0.88rem;
          color: var(--deepdoc-brand-dark);
          background: color-mix(in srgb, white 92%, var(--deepdoc-brand-light) 8%);
        }

        .deepdoc-chatbot-page__grid {
          display: grid;
          grid-template-columns: minmax(0, 1.45fr) minmax(18rem, 0.85fr);
          gap: 1.25rem;
          align-items: start;
        }

        .deepdoc-chatbot-page__grid > * {
          min-width: 0;
        }

        .deepdoc-chatbot-panel,
        .deepdoc-chatbot-sidebar {
          min-width: 0;
          border: 1px solid color-mix(in srgb, var(--deepdoc-brand-light) 14%, var(--color-fd-border) 86%);
          border-radius: 1.5rem;
          background: color-mix(in srgb, white 96%, var(--deepdoc-brand-light) 4%);
          box-shadow: 0 20px 60px rgba(131, 39, 25, 0.08);
        }

        .deepdoc-chatbot-sidebar {
          position: sticky;
          top: 1.5rem;
          padding: 1rem;
        }

        .deepdoc-chatbot-panel__header,
        .deepdoc-chatbot-sidebar__header {
          margin-bottom: 1rem;
          padding-bottom: 0.85rem;
          border-bottom: 1px solid color-mix(in srgb, var(--deepdoc-brand-light) 10%, var(--color-fd-border) 90%);
        }

        .deepdoc-chatbot-panel__header {
          padding: 1.2rem 1.25rem 0;
          background: transparent;
        }

        .deepdoc-chatbot-panel__body {
          padding: 0 1.25rem 1.25rem;
        }

        .deepdoc-chatbot-panel__question {
          margin: 0;
          font-size: 0.84rem;
          font-weight: 600;
          color: var(--color-fd-muted-foreground);
          text-transform: uppercase;
          letter-spacing: 0.06em;
        }

        .deepdoc-chatbot-panel__section-title {
          color: var(--deepdoc-brand-dark);
        }

        .deepdoc-chatbot-panel__empty {
          border: 1px dashed color-mix(in srgb, var(--deepdoc-brand-light) 22%, var(--color-fd-border) 78%);
          border-radius: 1.2rem;
          padding: 1.2rem;
          color: var(--color-fd-muted-foreground);
          background: color-mix(in srgb, white 94%, var(--deepdoc-brand-light) 6%);
        }

        .deepdoc-chatbot-skeleton {
          display: grid;
          gap: 0.85rem;
        }

        .deepdoc-chatbot-skeleton__block,
        .deepdoc-chatbot-skeleton__line,
        .deepdoc-chatbot-skeleton__card {
          position: relative;
          overflow: hidden;
          background: color-mix(in srgb, white 84%, var(--deepdoc-brand-light) 16%);
        }

        .deepdoc-chatbot-skeleton__block::after,
        .deepdoc-chatbot-skeleton__line::after,
        .deepdoc-chatbot-skeleton__card::after {
          content: '';
          position: absolute;
          inset: 0;
          transform: translateX(-100%);
          background: linear-gradient(
            90deg,
            transparent 0%,
            rgba(255, 255, 255, 0.66) 50%,
            transparent 100%
          );
          animation: deepdoc-chatbot-skeleton-shimmer 1.7s ease-in-out infinite;
        }

        .deepdoc-chatbot-skeleton__block {
          height: 12rem;
          border-radius: 1.2rem;
        }

        .deepdoc-chatbot-skeleton__line {
          height: 0.82rem;
          border-radius: 999px;
        }

        .deepdoc-chatbot-skeleton__line--sm {
          width: 28%;
        }

        .deepdoc-chatbot-skeleton__line--md {
          width: 56%;
        }

        .deepdoc-chatbot-skeleton__line--lg {
          width: 82%;
        }

        .deepdoc-chatbot-skeleton__line--full {
          width: 100%;
        }

        .deepdoc-chatbot-skeleton__cards {
          display: grid;
          gap: 0.85rem;
        }

        .deepdoc-chatbot-skeleton__card {
          height: 5.6rem;
          border-radius: 1rem;
        }

        @keyframes deepdoc-chatbot-skeleton-shimmer {
          100% {
            transform: translateX(100%);
          }
        }

        .deepdoc-chatbot-citation-list {
          display: grid;
          gap: 0.75rem;
        }

        .deepdoc-chatbot-citation-list li {
          min-width: 0;
          border: 1px solid color-mix(in srgb, var(--deepdoc-brand-light) 14%, var(--color-fd-border) 86%);
          border-radius: 1rem;
          padding: 0.8rem 0.9rem;
          background: white;
        }

        .deepdoc-chatbot-citation-list strong {
          display: block;
          margin-bottom: 0.2rem;
          color: #2f120d;
          overflow-wrap: anywhere;
          word-break: break-word;
        }

        .deepdoc-chatbot-citation-list span {
          display: block;
          font-size: 0.88rem;
          color: var(--color-fd-muted-foreground);
          overflow-wrap: anywhere;
          word-break: break-word;
        }

        .deepdoc-chatbot-citation-list a,
        .deepdoc-chatbot-answer a,
        main a {
          color: var(--deepdoc-brand-dark);
          text-decoration-color: color-mix(in srgb, var(--deepdoc-brand-primary) 36%, currentColor 64%);
        }

        .deepdoc-chatbot-citation-list a:hover,
        .deepdoc-chatbot-answer a:hover,
        main a:hover {
          color: var(--deepdoc-brand-primary);
        }

        ::selection {
          background: color-mix(in srgb, var(--deepdoc-brand-light) 28%, white 72%);
          color: #2f120d;
        }

        .deepdoc-chatbot-answer {
          overflow-wrap: anywhere;
        }

        .deepdoc-chatbot-answer__pre {
          margin: 1rem 0;
          overflow: hidden;
          border: 1px solid color-mix(in srgb, var(--deepdoc-brand-light) 10%, var(--color-fd-border) 90%);
          border-radius: 1.05rem;
          background:
            linear-gradient(180deg, rgba(36, 38, 53, 0.98), rgba(20, 21, 32, 1));
          box-shadow:
            inset 0 1px 0 rgba(255, 255, 255, 0.04),
            0 18px 40px rgba(17, 24, 39, 0.16);
        }

        .deepdoc-chatbot-answer__pre-header {
          display: flex;
          align-items: center;
          justify-content: space-between;
          gap: 0.75rem;
          padding: 0.7rem 0.9rem;
          border-bottom: 1px solid rgba(255, 255, 255, 0.06);
          background: rgba(255, 255, 255, 0.03);
        }

        .deepdoc-chatbot-answer__pre-dots {
          display: inline-flex;
          gap: 0.35rem;
        }

        .deepdoc-chatbot-answer__pre-dots span {
          height: 0.55rem;
          width: 0.55rem;
          border-radius: 999px;
          background: rgba(255, 255, 255, 0.2);
        }

        .deepdoc-chatbot-answer__pre-dots span:nth-child(1) {
          background: #f38ba8;
        }

        .deepdoc-chatbot-answer__pre-dots span:nth-child(2) {
          background: #f9e2af;
        }

        .deepdoc-chatbot-answer__pre-dots span:nth-child(3) {
          background: #a6e3a1;
        }

        .deepdoc-chatbot-answer__pre-label {
          font-size: 0.72rem;
          font-weight: 600;
          letter-spacing: 0.08em;
          text-transform: uppercase;
          color: rgba(226, 232, 240, 0.72);
        }

        .deepdoc-chatbot-answer__pre pre {
          margin: 0;
          overflow-x: auto;
          padding: 1rem 1.05rem 1.1rem;
          background: #181a27 !important;
          border: none;
          color: #e5e7eb !important;
        }

        .deepdoc-chatbot-answer__pre code {
          display: block;
          font-family: 'SF Mono', 'JetBrains Mono', 'Fira Code', 'Menlo', monospace;
          font-size: 0.88rem;
          line-height: 1.72;
          color: #e5e7eb !important;
          background: transparent !important;
          white-space: pre;
        }

        .deepdoc-chatbot-answer__syntax {
          background: #181a27;
        }

        .deepdoc-chatbot-answer__syntax code,
        .deepdoc-chatbot-answer__syntax span {
          font-family: 'SF Mono', 'JetBrains Mono', 'Fira Code', 'Menlo', monospace;
        }

        .deepdoc-chatbot-answer.prose :where(pre):not(:where([class~="not-prose"] *)) {
          margin: 0 !important;
          padding: 1rem 1.05rem 1.1rem !important;
          background: #181a27 !important;
          border: none !important;
          border-radius: 0 !important;
          box-shadow: none !important;
          color: #e5e7eb !important;
        }

        .deepdoc-chatbot-answer.prose :where(pre code):not(:where([class~="not-prose"] *)) {
          padding: 0 !important;
          background: transparent !important;
          border-radius: 0 !important;
          color: #e5e7eb !important;
          font-size: 0.88rem !important;
          line-height: 1.72 !important;
          white-space: pre !important;
          -webkit-text-fill-color: #e5e7eb;
        }

        .deepdoc-chatbot-answer__inline-code {
          display: inline-flex;
          align-items: center;
          border: 1px solid color-mix(in srgb, var(--deepdoc-brand-light) 12%, var(--color-fd-border) 88%);
          border-radius: 0.6rem;
          padding: 0.12rem 0.42rem;
          background: color-mix(in srgb, white 91%, var(--deepdoc-brand-light) 9%);
          color: var(--deepdoc-brand-dark);
          font-family: 'SF Mono', 'JetBrains Mono', 'Fira Code', 'Menlo', monospace;
          font-size: 0.875em;
        }

        .deepdoc-chatbot-answer__evidence-link {
          display: inline-flex;
          align-items: center;
          border: 1px solid color-mix(in srgb, var(--deepdoc-brand-light) 20%, var(--color-fd-border) 80%);
          border-radius: 999px;
          padding: 0.04rem 0.42rem;
          background: color-mix(in srgb, white 88%, var(--deepdoc-brand-light) 12%);
          color: var(--deepdoc-brand-dark);
          font-weight: 700;
          text-decoration: none;
          cursor: pointer;
        }

        .deepdoc-chatbot-answer p,
        .deepdoc-chatbot-answer ul,
        .deepdoc-chatbot-answer ol,
        .deepdoc-chatbot-answer pre,
        .deepdoc-chatbot-answer blockquote,
        .deepdoc-chatbot-answer h1,
        .deepdoc-chatbot-answer h2,
        .deepdoc-chatbot-answer h3,
        .deepdoc-chatbot-answer h4 {
          margin-top: 0.75rem;
          margin-bottom: 0.75rem;
        }

        .deepdoc-chatbot-answer ul,
        .deepdoc-chatbot-answer ol {
          padding-left: 1.25rem;
        }

        .deepdoc-chatbot-answer blockquote {
          border-left: 3px solid var(--color-fd-border);
          padding-left: 0.875rem;
          color: var(--color-fd-muted-foreground);
        }

        /* Clickable citation cards */
        .deepdoc-chatbot-citation-list__clickable {
          cursor: pointer;
          transition: transform 0.15s, border-color 0.15s, box-shadow 0.15s, background 0.15s;
        }

        .deepdoc-chatbot-citation-list__clickable:hover {
          transform: translateY(-1px);
          border-color: color-mix(in srgb, var(--deepdoc-brand-primary) 50%, white 50%) !important;
          box-shadow:
            0 0 0 1px color-mix(in srgb, var(--deepdoc-brand-primary) 34%, white 66%),
            0 14px 28px rgba(193, 51, 31, 0.08);
          background:
            linear-gradient(180deg, color-mix(in srgb, var(--deepdoc-brand-light) 4%, white 96%), white);
        }

        .deepdoc-chatbot-citation-list__clickable:focus-visible {
          outline: 2px solid var(--deepdoc-brand-primary);
          outline-offset: 2px;
        }

        .deepdoc-chatbot-section-hint {
          font-weight: 400;
          font-size: 0.75rem;
          color: var(--color-fd-muted-foreground);
        }

        .deepdoc-chatbot-citation-list__row {
          display: flex;
          align-items: center;
          justify-content: space-between;
          gap: 0.85rem;
        }

        .deepdoc-chatbot-citation-list__text {
          min-width: 0;
          flex: 1;
        }

        .deepdoc-chatbot-citation-list__action {
          flex-shrink: 0;
          display: inline-flex;
          align-items: center;
          gap: 0.35rem;
          border: 1px solid color-mix(in srgb, var(--deepdoc-brand-light) 12%, var(--color-fd-border) 88%);
          border-radius: 999px;
          padding: 0.32rem 0.56rem;
          font-size: 0.72rem;
          font-weight: 600;
          color: var(--deepdoc-brand-dark);
          background: color-mix(in srgb, white 93%, var(--deepdoc-brand-light) 7%);
        }

        .deepdoc-chatbot-citation-list__action::after {
          content: '↗';
          font-size: 0.78rem;
        }

        .deepdoc-chatbot-trace {
          border: 1px solid color-mix(in srgb, var(--deepdoc-brand-light) 14%, var(--color-fd-border) 86%);
          border-radius: 1rem;
          padding: 0.85rem 0.9rem;
          background: color-mix(in srgb, white 96%, var(--deepdoc-brand-light) 4%);
        }

        .deepdoc-chatbot-trace__header {
          display: flex;
          align-items: center;
          gap: 0.55rem;
          margin-bottom: 0.6rem;
          color: #2f120d;
          font-size: 0.93rem;
        }

        .deepdoc-chatbot-trace__header strong {
          flex: 1;
          min-width: 0;
          font-weight: 600;
          color: inherit;
        }

        .deepdoc-chatbot-trace__header span {
          font-size: 0.82rem;
          color: var(--color-fd-muted-foreground);
        }

        .deepdoc-chatbot-trace__dot {
          width: 0.52rem;
          height: 0.52rem;
          border-radius: 999px;
          background: var(--deepdoc-brand-primary);
          box-shadow: 0 0 0 0 rgba(235, 62, 37, 0.4);
          animation: deepdoc-chatbot-trace-pulse 1.4s ease-in-out infinite;
          flex-shrink: 0;
        }

        .deepdoc-chatbot-trace__bar {
          width: 100%;
          height: 0.42rem;
          border-radius: 999px;
          background: color-mix(in srgb, var(--deepdoc-brand-light) 14%, white 86%);
          overflow: hidden;
          margin-bottom: 0.72rem;
        }

        .deepdoc-chatbot-trace__bar > span {
          display: block;
          height: 100%;
          border-radius: inherit;
          background: linear-gradient(90deg, var(--deepdoc-brand-light), var(--deepdoc-brand-primary));
          transition: width 180ms ease;
        }

        .deepdoc-chatbot-trace__lines {
          margin: 0;
          padding: 0;
          max-height: 11.25rem;
          overflow-y: auto;
          list-style: none;
          display: grid;
          gap: 0.36rem;
        }

        .deepdoc-chatbot-trace__lines li {
          display: block;
          font-size: 0.87rem;
          line-height: 1.35;
          color: var(--color-fd-muted-foreground);
          opacity: 0.8;
          white-space: nowrap;
          overflow: hidden;
          text-overflow: ellipsis;
          padding-left: 0.75rem;
          position: relative;
        }

        .deepdoc-chatbot-trace__lines li::before {
          content: '-';
          position: absolute;
          left: 0;
          color: color-mix(in srgb, var(--deepdoc-brand-primary) 56%, var(--color-fd-muted-foreground) 44%);
        }

        @keyframes deepdoc-chatbot-trace-pulse {
          0% {
            box-shadow: 0 0 0 0 rgba(235, 62, 37, 0.3);
          }
          70% {
            box-shadow: 0 0 0 0.48rem rgba(235, 62, 37, 0);
          }
          100% {
            box-shadow: 0 0 0 0 rgba(235, 62, 37, 0);
          }
        }

        /* Code modal overlay */
        .deepdoc-code-modal-overlay {
          position: fixed;
          inset: 0;
          z-index: 9999;
          display: flex;
          align-items: center;
          justify-content: center;
          background:
            radial-gradient(circle at top, rgba(235, 62, 37, 0.12), transparent 30%),
            rgba(9, 11, 19, 0.6);
          backdrop-filter: blur(6px);
          animation: deepdoc-modal-fadein 0.15s ease-out;
        }

        @keyframes deepdoc-modal-fadein {
          from { opacity: 0; }
          to { opacity: 1; }
        }

        .deepdoc-code-modal {
          width: min(92vw, 64rem);
          max-height: 84vh;
          display: flex;
          flex-direction: column;
          background: #171824;
          border: 1px solid rgba(255, 255, 255, 0.08);
          border-radius: 1.2rem;
          box-shadow: 0 30px 80px rgba(0, 0, 0, 0.5);
          overflow: hidden;
          animation: deepdoc-modal-scalein 0.15s ease-out;
        }

        @keyframes deepdoc-modal-scalein {
          from { transform: scale(0.96); opacity: 0; }
          to { transform: scale(1); opacity: 1; }
        }

        .deepdoc-code-modal__header {
          display: flex;
          align-items: center;
          justify-content: space-between;
          gap: 1rem;
          padding: 0.95rem 1.1rem;
          background:
            linear-gradient(180deg, rgba(255, 255, 255, 0.025), rgba(255, 255, 255, 0));
          border-bottom: 1px solid rgba(255, 255, 255, 0.06);
        }
        .deepdoc-code-modal__title strong {
          display: block;
          color: #cdd6f4;
          font-size: 0.875rem;
          font-weight: 600;
          overflow-wrap: anywhere;
        }
        .deepdoc-code-modal__title span {
          display: block;
          font-size: 0.75rem;
          color: #6c7086;
          margin-top: 0.1rem;
        }
        .deepdoc-code-modal__close {
          flex-shrink: 0;
          width: 2rem;
          height: 2rem;
          display: flex;
          align-items: center;
          justify-content: center;
          border: none;
          border-radius: 0.5rem;
          background: transparent;
          color: #6c7086;
          font-size: 1rem;
          cursor: pointer;
          transition: background 0.12s, color 0.12s;
        }
        .deepdoc-code-modal__close:hover {
          background: rgba(255, 255, 255, 0.08);
          color: #cdd6f4;
        }

        /* Metadata strip */
        .deepdoc-code-modal__meta {
          display: flex;
          flex-direction: column;
          gap: 0.4rem;
          padding: 0.7rem 1.1rem;
          background: #11131c;
          border-bottom: 1px solid rgba(255, 255, 255, 0.06);
        }
        .deepdoc-code-modal__meta-row {
          display: flex;
          align-items: baseline;
          gap: 0.5rem;
          flex-wrap: wrap;
        }
        .deepdoc-code-modal__meta-label {
          flex-shrink: 0;
          font-size: 0.68rem;
          font-weight: 600;
          text-transform: uppercase;
          letter-spacing: 0.06em;
          color: #585b70;
          min-width: 4.5rem;
        }
        .deepdoc-code-modal__meta-tags {
          display: flex;
          flex-wrap: wrap;
          gap: 0.3rem;
        }
        .deepdoc-code-modal__tag {
          display: inline-block;
          padding: 0.12rem 0.5rem;
          border-radius: 999px;
          font-size: 0.72rem;
          font-family: 'SF Mono', 'Fira Code', 'JetBrains Mono', 'Menlo', monospace;
          background: rgba(137, 180, 250, 0.12);
          color: #89b4fa;
          border: 1px solid rgba(137, 180, 250, 0.15);
        }
        .deepdoc-code-modal__tag--dim {
          background: rgba(108, 112, 134, 0.1);
          color: #a6adc8;
          border-color: rgba(108, 112, 134, 0.15);
        }
        .deepdoc-code-modal__sig {
          font-size: 0.76rem;
          font-family: 'SF Mono', 'Fira Code', 'JetBrains Mono', 'Menlo', monospace;
          color: #a6e3a1;
          background: rgba(166, 227, 161, 0.08);
          padding: 0.1rem 0.45rem;
          border-radius: 0.3rem;
          border: 1px solid rgba(166, 227, 161, 0.12);
        }

        /* Code block */
        .deepdoc-code-modal__body {
          flex: 1;
          overflow: auto;
          padding: 0.75rem 0 0.9rem;
          background:
            linear-gradient(180deg, rgba(255, 255, 255, 0.02), rgba(255, 255, 255, 0)),
            #181a27;
        }
        .deepdoc-code-modal__syntax {
          min-width: 100%;
        }
        .deepdoc-code-modal__syntax pre {
          margin: 0 !important;
          background: transparent !important;
          border: none !important;
          border-radius: 0 !important;
          padding: 0 !important;
        }
        .deepdoc-code-modal__syntax code {
          font-family: 'SF Mono', 'Fira Code', 'JetBrains Mono', 'Menlo', monospace !important;
          font-size: 0.8125rem !important;
          line-height: 1.7 !important;
          tab-size: 4;
        }
        .deepdoc-code-modal__plain-fallback {
          margin: 0;
          padding: 0 1rem;
          white-space: pre;
          font-family: 'SF Mono', 'Fira Code', 'JetBrains Mono', 'Menlo', monospace;
          font-size: 0.8125rem;
          line-height: 1.7;
          color: #cdd6f4;
          tab-size: 4;
        }

        :is(.dark, [data-theme='dark']) .deepdoc-chatbot-page__back {
          color: rgba(226, 232, 240, 0.76);
        }

        :is(.dark, [data-theme='dark']) .deepdoc-chatbot-page__back:hover {
          color: #f8d1ca;
        }

        :is(.dark, [data-theme='dark']) .deepdoc-chatbot-page__eyebrow,
        :is(.dark, [data-theme='dark']) .deepdoc-chatbot-dock__eyebrow,
        :is(.dark, [data-theme='dark']) .deepdoc-chatbot-panel__section-title,
        :is(.dark, [data-theme='dark']) .deepdoc-chatbot-citation-list__action,
        :is(.dark, [data-theme='dark']) .deepdoc-chatbot-answer__inline-code {
          color: #ffd7cf;
        }

        :is(.dark, [data-theme='dark']) .deepdoc-chatbot-page__hero h1 {
          color: #fff5f2;
        }

        :is(.dark, [data-theme='dark']) .deepdoc-chatbot-page__hero p,
        :is(.dark, [data-theme='dark']) .deepdoc-chatbot-dock__hint,
        :is(.dark, [data-theme='dark']) .deepdoc-chatbot-panel__question,
        :is(.dark, [data-theme='dark']) .deepdoc-chatbot-panel__empty,
        :is(.dark, [data-theme='dark']) .deepdoc-chatbot-citation-list span,
        :is(.dark, [data-theme='dark']) .deepdoc-chatbot-section-hint {
          color: rgba(226, 232, 240, 0.72);
        }

        :is(.dark, [data-theme='dark']) .deepdoc-chatbot-page__chip {
          border-color: rgba(255, 255, 255, 0.1);
          background: rgba(255, 237, 233, 0.08);
          color: #ffcabf;
        }

        :is(.dark, [data-theme='dark']) .deepdoc-chatbot-dock,
        :is(.dark, [data-theme='dark']) .deepdoc-chatbot-panel,
        :is(.dark, [data-theme='dark']) .deepdoc-chatbot-sidebar {
          border-color: rgba(255, 255, 255, 0.08);
          background:
            linear-gradient(180deg, rgba(255, 255, 255, 0.03), rgba(255, 255, 255, 0.015)),
            #14151f;
          box-shadow:
            0 24px 60px rgba(0, 0, 0, 0.34),
            inset 0 1px 0 rgba(255, 255, 255, 0.025);
        }

        :is(.dark, [data-theme='dark']) .deepdoc-chatbot-panel__header,
        :is(.dark, [data-theme='dark']) .deepdoc-chatbot-sidebar__header {
          border-bottom-color: rgba(255, 255, 255, 0.08);
        }

        :is(.dark, [data-theme='dark']) .deepdoc-chatbot-dock__input,
        :is(.dark, [data-theme='dark']) .deepdoc-chatbot-panel__input {
          border-color: rgba(255, 255, 255, 0.08);
          background: #10111a;
          color: #f8fafc;
          box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.03);
        }

        :is(.dark, [data-theme='dark']) .deepdoc-chatbot-dock__input::placeholder,
        :is(.dark, [data-theme='dark']) .deepdoc-chatbot-panel__input::placeholder {
          color: rgba(226, 232, 240, 0.42);
        }

        :is(.dark, [data-theme='dark']) .deepdoc-chatbot-panel__empty {
          border-color: rgba(255, 255, 255, 0.12);
          background: rgba(255, 255, 255, 0.02);
        }

        :is(.dark, [data-theme='dark']) .deepdoc-chatbot-skeleton__block,
        :is(.dark, [data-theme='dark']) .deepdoc-chatbot-skeleton__line,
        :is(.dark, [data-theme='dark']) .deepdoc-chatbot-skeleton__card {
          background: rgba(255, 255, 255, 0.07);
        }

        :is(.dark, [data-theme='dark']) .deepdoc-chatbot-skeleton__block::after,
        :is(.dark, [data-theme='dark']) .deepdoc-chatbot-skeleton__line::after,
        :is(.dark, [data-theme='dark']) .deepdoc-chatbot-skeleton__card::after {
          background: linear-gradient(
            90deg,
            transparent 0%,
            rgba(255, 255, 255, 0.12) 50%,
            transparent 100%
          );
        }

        :is(.dark, [data-theme='dark']) .deepdoc-chatbot-citation-list li {
          border-color: rgba(255, 255, 255, 0.08);
          background:
            linear-gradient(180deg, rgba(255, 255, 255, 0.03), rgba(255, 255, 255, 0.015)),
            #11131c;
        }

        :is(.dark, [data-theme='dark']) .deepdoc-chatbot-citation-list strong {
          color: #fff1ed;
        }

        :is(.dark, [data-theme='dark']) .deepdoc-chatbot-citation-list__clickable:hover {
          border-color: rgba(255, 202, 191, 0.42) !important;
          box-shadow:
            0 0 0 1px rgba(255, 202, 191, 0.16),
            0 14px 28px rgba(0, 0, 0, 0.24);
          background:
            linear-gradient(180deg, rgba(255, 255, 255, 0.045), rgba(255, 255, 255, 0.02)),
            #141722;
        }

        :is(.dark, [data-theme='dark']) .deepdoc-chatbot-citation-list__action {
          border-color: rgba(255, 255, 255, 0.08);
          background: rgba(255, 237, 233, 0.06);
        }

        :is(.dark, [data-theme='dark']) .deepdoc-chatbot-trace {
          border-color: rgba(255, 255, 255, 0.1);
          background:
            linear-gradient(180deg, rgba(255, 255, 255, 0.03), rgba(255, 255, 255, 0.015)),
            #131520;
        }

        :is(.dark, [data-theme='dark']) .deepdoc-chatbot-trace__header {
          color: #fff1ed;
        }

        :is(.dark, [data-theme='dark']) .deepdoc-chatbot-trace__header span,
        :is(.dark, [data-theme='dark']) .deepdoc-chatbot-trace__lines li {
          color: rgba(226, 232, 240, 0.72);
        }

        :is(.dark, [data-theme='dark']) .deepdoc-chatbot-trace__bar {
          background: rgba(255, 255, 255, 0.09);
        }

        :is(.dark, [data-theme='dark']) .deepdoc-chatbot-answer__inline-code,
        :is(.dark, [data-theme='dark']) .deepdoc-chatbot-answer__evidence-link {
          border-color: rgba(255, 255, 255, 0.08);
          background: rgba(255, 237, 233, 0.08);
        }

        :is(.dark, [data-theme='dark']) .deepdoc-chatbot-answer blockquote {
          border-left-color: rgba(255, 255, 255, 0.14);
          color: rgba(226, 232, 240, 0.78);
        }

        @media (max-width: 960px) {
          .deepdoc-chatbot-page__grid {
            grid-template-columns: minmax(0, 1fr);
          }

          .deepdoc-chatbot-sidebar {
            position: static;
          }
        }

        @media (max-width: 640px) {
          body {
            padding-bottom: 9.5rem;
          }

          .deepdoc-chatbot-shell {
            width: calc(100vw - 1rem);
            bottom: 0.5rem;
          }

          .deepdoc-chatbot-dock {
            padding: 0.8rem;
            border-radius: 1.2rem;
          }

          .deepdoc-chatbot-dock__meta,
          .deepdoc-chatbot-dock__row,
          .deepdoc-chatbot-page__hero {
            display: grid;
            grid-template-columns: minmax(0, 1fr);
          }

          .deepdoc-chatbot-dock__hint {
            max-width: none;
            text-align: left;
          }

          .deepdoc-chatbot-dock__submit,
          .deepdoc-chatbot-panel__button {
            width: 100%;
            justify-content: center;
          }

          .deepdoc-chatbot-page {
            width: min(calc(100vw - 1rem), 100%);
            padding-top: 1.35rem;
          }

          .deepdoc-chatbot-panel__header,
          .deepdoc-chatbot-panel__body,
          .deepdoc-chatbot-sidebar {
            padding-left: 1rem;
            padding-right: 1rem;
          }
        }
        """
    )
    return (
        (base_css + (chatbot_css if chatbot_enabled else "")).replace("__PRIMARY__", primary)
        .replace("__LIGHT__", light)
        .replace("__DARK__", dark)
    )


def _search_route_ts() -> str:
    return dedent(
        """\
        import { docsSource } from '@/lib/source';
        import { createFromSource } from 'fumadocs-core/search/server';

        export const revalidate = false;
        export const { staticGET: GET } = createFromSource(docsSource);
        """
    )


def _docs_layout_tsx() -> str:
    return dedent(
        """\
        import { DocsLayout } from 'fumadocs-ui/layouts/docs';
        import { layoutOptions } from '@/lib/layout-options';
        import { pageTree } from '@/lib/page-tree.generated';
        import type { ReactNode } from 'react';

        export default function Layout({ children }: { children: ReactNode }) {
          return (
            <DocsLayout tree={pageTree} {...layoutOptions}>
              {children}
            </DocsLayout>
          );
        }
        """
    )


def _docs_page_tsx() -> str:
    return dedent(
        """\
        import { notFound } from 'next/navigation';
        import { DocsBody, DocsPage } from 'fumadocs-ui/page';
        import { docsSource } from '@/lib/source';
        import { getMDXComponents } from '@/mdx-components';
        import type { ComponentType } from 'react';
        import type { TOCItemType } from 'fumadocs-core/server';

        export function generateStaticParams() {
          return docsSource.generateParams();
        }

        export default async function Page(props: {
          params: Promise<{ slug?: string[] }>;
        }) {
          const params = await props.params;
          const page = docsSource.getPage(params.slug ?? []);
          if (!page) notFound();

          const MDX = (page.data as { body: ComponentType<{ components?: ReturnType<typeof getMDXComponents> }> }).body;
          const toc = (page.data as { toc?: TOCItemType[] }).toc;

          return (
            <DocsPage toc={toc}>
              <DocsBody>
                <MDX components={getMDXComponents()} />
              </DocsBody>
            </DocsPage>
          );
        }
        """
    )


def _api_layout_tsx() -> str:
    return _docs_layout_tsx()


def _api_page_tsx() -> str:
    return dedent(
        """\
        import { notFound } from 'next/navigation';
        import { DocsBody, DocsPage } from 'fumadocs-ui/page';
        import { APIPage } from '@/components/api-page';
        import { generateAPIParams, getAPIPage } from '@/lib/openapi';

        export function generateStaticParams() {
          return generateAPIParams();
        }

        export default async function Page(props: {
          params: Promise<{ slug?: string[] }>;
        }) {
          const params = await props.params;
          const page = getAPIPage(params.slug ?? []);
          if (!page || page.data.type !== 'openapi') notFound();

          return (
            <DocsPage full>
              <DocsBody>
                <APIPage {...page.data.getAPIPageProps()} />
              </DocsBody>
            </DocsPage>
          );
        }
        """
    )


def _chatbot_ask_page_tsx() -> str:
    return dedent(
        """\
        import { Suspense } from 'react';
        import { ChatbotPanel } from '@/components/chatbot-panel';

        export default function AskPage() {
          return (
            <Suspense fallback={null}>
              <ChatbotPanel />
            </Suspense>
          );
        }
        """
    )


def _api_page_component_tsx() -> str:
    return dedent(
        """\
        import { openapi } from '@/lib/openapi';
        import { APIPage as FumadocsAPIPage } from 'fumadocs-openapi/ui';
        import type { ApiPageProps } from 'fumadocs-openapi/ui';

        function EmptyAPIPage(_: ApiPageProps) {
          return null;
        }

        export function APIPage(props: ApiPageProps) {
          if (!openapi) return EmptyAPIPage(props);
          return <FumadocsAPIPage {...openapi.getAPIPageProps(props)} />;
        }
        """
    )


def _api_page_client_tsx() -> str:
    return dedent(
        """\
        const client = {};

        export default client;
        """
    )


def _mermaid_component_tsx() -> str:
    return dedent(
        """\
        'use client';

        import { use, useEffect, useId, useState } from 'react';
        import { useTheme } from 'next-themes';

        export function Mermaid({ chart }: { chart: string }) {
          const [mounted, setMounted] = useState(false);

          useEffect(() => {
            setMounted(true);
          }, []);

          if (!mounted) return null;
          return <MermaidContent chart={chart} />;
        }

        const cache = new Map<string, Promise<unknown>>();

        function cachePromise<T>(key: string, setPromise: () => Promise<T>): Promise<T> {
          const cached = cache.get(key);
          if (cached) return cached as Promise<T>;

          const promise = setPromise();
          cache.set(key, promise);
          return promise;
        }

        function MermaidContent({ chart }: { chart: string }) {
          const id = useId();
          const { resolvedTheme } = useTheme();
          const { default: mermaid } = use(
            cachePromise('mermaid', () => import('mermaid')),
          );

          mermaid.initialize({
            startOnLoad: false,
            securityLevel: 'loose',
            fontFamily: 'inherit',
            themeCSS: 'margin: 1.5rem auto 0;',
            theme: resolvedTheme === 'dark' ? 'dark' : 'default',
          });

          const { svg, bindFunctions } = use(
            cachePromise(`${chart}-${resolvedTheme}`, () => {
              return mermaid.render(id, chart.replaceAll('\\\\n', '\\n'));
            }),
          );

          return (
            <div
              ref={(container) => {
                if (container) bindFunctions?.(container);
              }}
              dangerouslySetInnerHTML={{ __html: svg }}
            />
          );
        }
        """
    )


def _source_ts() -> str:
    return dedent(
        """\
        import { resolveFiles } from 'fumadocs-mdx';
        import { loader } from 'fumadocs-core/source';
        import { docs, meta } from '@/.source';

        export const docsSource = loader({
          baseUrl: '/',
          source: {
            files: resolveFiles({ docs, meta }),
          },
        });
        """
    )


def _layout_options_ts(project_name: str, repo_url: str) -> str:
    links = f"[{{ text: 'GitHub', url: '{repo_url}' }}]" if repo_url else "[]"
    return dedent(
        f"""\
        export const layoutOptions = {{
          nav: {{
            title: '{project_name}',
            url: '/',
          }},
          links: {links},
        }};
        """
    )


def _openapi_ts() -> str:
    return dedent(
        """\
        import fs from 'node:fs';
        import path from 'node:path';
        import { createOpenAPI } from 'fumadocs-openapi/server';
        import type { ApiPageProps } from 'fumadocs-openapi/ui';

        const schemaDir = path.join(process.cwd(), 'openapi');
        const schemaFiles = fs.existsSync(schemaDir)
          ? fs
              .readdirSync(schemaDir)
              .filter(
                (file) =>
                  /\\.(json|ya?ml)$/i.test(file) &&
                  !/^manifest\\.json$/i.test(file) &&
                  /^(openapi|swagger)(\\.|$)/i.test(file),
              )
              .map((file) => path.join(schemaDir, file))
          : [];

        export const openapi =
          schemaFiles.length > 0
            ? createOpenAPI({
                input: schemaFiles,
              })
            : null;

        type ManifestEntry = {
          slug: string;
          title: string;
          method: string;
          path: string;
        };

        const manifestPath = path.join(schemaDir, 'manifest.json');
        const apiManifest: ManifestEntry[] = fs.existsSync(manifestPath)
          ? JSON.parse(fs.readFileSync(manifestPath, 'utf8'))
          : [];

        export function generateAPIParams() {
          return apiManifest.map((entry) => ({
            slug: entry.slug.split('/').filter(Boolean),
          }));
        }

        export function getAPIPage(slugs: string[]) {
          if (!openapi || schemaFiles.length === 0) return null;

          const slug = slugs.join('/');
          const entry = apiManifest.find((item) => item.slug === slug);
          if (!entry) return null;

          return {
            url: `/api/${entry.slug}`,
            data: {
              type: 'openapi' as const,
              title: entry.title,
              getAPIPageProps(): ApiPageProps {
                return {
                  document: schemaFiles[0],
                  hasHead: true,
                  operations: [
                    {
                      path: entry.path,
                      method: entry.method.toLowerCase() as Lowercase<ManifestEntry['method']>,
                    },
                  ],
                };
              },
            },
          };
        }
        """
    )
